### ISSUE TITLE
Only show x axis ticks that have series data

### ISSUE THREAD

**Issue by lucasgray** [knowm/XChart#132]
For Line charts that have Dates as X axis, we'd ideally like to display only x axis ticks that have data.  What ends up happening for us, is that since Date is (nicely!) treated as continuous, if we have less than a certain number of dates in the data, we get ticks for which there is no data.  Making matters worse, we default to "EEE" (shortened day of week) for the date format label, which results in labels like Mon, Mon... instead of Mon 00:00, Mon 12:00, etc.  It's confusing to end users.  For example...

![pastedimage](https://cloud.githubusercontent.com/assets/293351/12621741/94f93238-c4e7-11e5-8432-4a101ec33fcc.png)

Is there a way to ask xChart to only display x tick marks that have series data, or otherwise tell xChart that we only want [x] amount of ticks, so we can set the value ourselves?  I see the padding hint, but had trouble setting that to the correct value.

**Comment by timmolter** [comment]
@lucasgray Admittedly, the algorithm I developed for auto-generating the data formatter to use is not perfect. I spent a very long time developing what I have now, and it's not perfect, but it's close. For the non-perfect cases, you need to set the formatting String manually.

> we default to "EEE" (shortened day of week) for the date format label,

Are you manually setting that or is XChart automatically setting that?

You cannot tell XChart how many points you want, but you can influence it with the following style code:

    chart.getStyler().setXAxisTickMarkSpacingHint(400);

Alternately, you could try a `Chart_Category` chart type.

**Comment by shavakagrawal** [comment]
Hi,
Is there still any method to only use the dates which have some data in them? I have data which have values on all days except weekends and would hence like to exclude those dates.
Thanks!

**Comment by timmolter** [comment]
This should be possible via the new custom axis tick calculator. Is this correct @hakantkn ??

**Comment by hakantkn** [comment]
Yes, it is possible. See details at https://github.com/knowm/XChart#customizing-axis-ticks--axis-labels
