### ISSUE TITLE
X-Axis with null data

### ISSUE THREAD

**Issue by shd89** [knowm/XChart#153]
Hello,
I am trying to use the library with inverted axis. I am plotting values against depth. 
example:

> ```
>     ArrayList<Double> xdata = new ArrayList<Double>();
>     xdata.add(600.0);
>     xdata.add(125.0);
>     xdata.add(350.0);
>     xdata.add(150.0);
>     xdata.add(400.0);
>     xdata.add(380.0);
>     xdata.add(450.0);
>     ArrayList<Double> ydata = new ArrayList<Double>();
>     ydata.add(0.0);
>     ydata.add(-1.0);
>     ydata.add(-2.0);
>     ydata.add(-3.0);
>     ydata.add(-4.0);
>     ydata.add(-5.0);
>     ydata.add(-6.0);
>     XYChart chart1 = new XYChartBuilder().width(200).height(480).title("").xAxisTitle("Thrust (kgf)").yAxisTitle("Depth (m)").theme(Styler.ChartTheme.Matlab).build();
>     chart1.getStyler().setDefaultSeriesRenderStyle(XYSeries.XYSeriesRenderStyle.Line);
>     chart1.getStyler().setChartTitleVisible(false);
>     chart1.getStyler().setLegendVisible(false);
>     chart1.getStyler().setMarkerSize(3);
>     chart1.addSeries("data", xdata, ydata);
> ```

![image](https://cloud.githubusercontent.com/assets/19352858/15261017/9b34a808-191f-11e6-962a-00a7c7c35bf2.png)

The data isn't provided for some depths. When one of the xdata values is null, I get an exception in thread "AWT-EventQueue-0" java.lang.NullPointerException.
Am I doing something wrong? Is there a possibility to have a plot similar to the one in the example "AreaChart02 - Null Y-Axis Data Points", but with null X-Axis data points?
Thank you!

**Comment by timmolter** [comment]
No, that's not possible right now. I'll leave this open as a feature request.

**Comment by shd89** [comment]
Thank you.
I already found a way around it.

**Comment by Mr14huashao** [comment]
already fixed
