### ISSUE TITLE
Feature request: Histogram with numeric x axis

### ISSUE THREAD

**Issue by lwhite1** [knowm/XChart#157]
It looks like the current histogram is built on categoryChart, and so each bar has its own label like a traditional bar chart. Most histograms in statistical software have a numeric x axis, so that the distribution can be suggested with fewer labels when space is at a premium, or when there are many bars or large numerical labels. 

PS. Clearly the XChart is very popular and you have many feature requests. Thank you for considering this one.

**Comment by timmolter** [comment]
Yes, that'd be a good new feature. I will add that when I have time, but it won't be for a while. I need to add a `Bar` style to the `XYSeriesRenderStyle` enum and the corresponding render logic.

**Comment by timmolter** [comment]
Actually, we don't need a new chart type for this. Just use the `Histogram` class as demonstrated in `BarChart06`.
