### ISSUE TITLE
Too many value labels on x axis?

### ISSUE THREAD

**Issue by johannescarlen** [knowm/XChart#159]
Plotting five points as image shows. The graph however displays labels on the x axis inbetween these points. Doesn't seem to be possible to prevent this?

Enclosing example code to replicate the problem.

![linechart](https://cloud.githubusercontent.com/assets/688236/18157983/a1e7c9ca-7020-11e6-8787-0967b04ccc22.png)

```
XYChart chart = new XYChartBuilder().width(800).height(600).title("LineChart").xAxisTitle("X").yAxisTitle("Y").build();

XYStyler styler = chart.getStyler();
styler.setChartTitleVisible(false);
styler.setLegendVisible(false);
styler.chartBackgroundColor = Color.white;

styler.axisTicksLineVisible = false;
styler.plotGridVerticalLinesVisible = false;

styler.setXAxisTitleVisible(false);
styler.setYAxisTitleVisible(false);

styler.setAxisTickLabelsColor(Color.darkGray);
styler.setDatePattern("MM-dd");
styler.setYAxisMin(1);
styler.setYAxisMax(10);


List<Date> xData = new ArrayList<Date>();
List<Integer> yData = new ArrayList<Integer>();

yData.add(1);
yData.add(2);
yData.add(4);
yData.add(8);
yData.add(10);

DateTime dt = DateTime.now().withTimeAtStartOfDay(); // Using joda
xData.add(dt.toDate());
xData.add(dt.plusDays(1).toDate());
xData.add(dt.plusDays(2).toDate());
xData.add(dt.plusDays(3).toDate());
xData.add(dt.plusDays(4).toDate());


// Series
XYSeries series = chart.addSeries("My Data", xData, yData);
series.setLineColor(XChartSeriesColors.RED);
series.setMarkerColor(Color.RED);
series.setMarker(SeriesMarkers.CIRCLE);
series.setLineStyle(SeriesLines.SOLID);
```

**Comment by timmolter** [comment]
There is no elegant solution for this (yet). What you can try is playing with the following:

    chart.getStyler().setXAxisTickMarkSpacingHint(200);

If you can think of a better solution on how to solve this in general, I can try to implement it.

**Comment by johannescarlen** [comment]
Ah ok, I see how that works. I will play some with that for now and later have a look at the source!

**Comment by shining01** [comment]
Hello,

i there a solution in sight? 
chart.getStyler().setXAxisTickMarkSpacingHint(200); this function does not work in my case. Thanks

**Comment by Mr14huashao** [comment]
@timmolter 
If there is no custom axis tick, can filter duplicate tickLabel?

```java
if (!tickLabels.contains(axisFormat.format(value))) {
  tickLabels.add(axisFormat.format(value));
}
```

**Comment by timmolter** [comment]
Adding `chart.getStyler().setXAxisTickMarkSpacingHint(200);` works for me, at least using the code in the latest xchart lib development code. Maybe it got fixed at some point??

<img width="800" alt="Screen Shot 2019-12-21 at 10 48 26" src="https://user-images.githubusercontent.com/738972/71306367-7a9cd880-23df-11ea-8c71-cb4ece0bd8fa.png">
<img width="800" alt="Screen Shot 2019-12-21 at 10 47 56" src="https://user-images.githubusercontent.com/738972/71306368-7a9cd880-23df-11ea-92bc-a700856850e8.png">

**Comment by timmolter** [comment]
I added a demo chart for this issue.
