### ISSUE TITLE
heatmap

### ISSUE THREAD

**Issue by rqcy** [knowm/XChart#164]
Hi, it would be very useful to have heat map available in XChart to visualize matrices: https://en.wikipedia.org/wiki/Heat_map

Thanks!

**Comment by timmolter** [comment]
Yes, I think that would be a cool feature and pretty easy to implement.

**Comment by rqcy** [comment]
cool! please consider implementing the default matplotlib's colormap: Viridis

[1] https://bids.github.io/colormap/
[2] https://www.youtube.com/watch?v=xAoljeRJ3lU

**Comment by ouryperd** [comment]
+1 for heatmap or treemap in xchart

**Comment by timmolter** [comment]
Similar to issue #65

**Comment by mccartney** [comment]
I think HeatMaps have already been implemented since then and this issue should be closed.

**Comment by ouryperd** [comment]
I meant a [treemap](https://www.cs.umd.edu/hcil/treemap-history/index.shtml). I don't think that is implemented.

**Comment by mccartney** [comment]
AFAIK HeapMaps are, TreeMaps are not.
@ouryperd - please create another issue for treemaps.
