### ISSUE TITLE
add dial chart

### ISSUE THREAD

**Issue by ningpp** [knowm/XChart#189]
![image](https://user-images.githubusercontent.com/2511498/27112078-24a8a88c-50e7-11e7-9cce-f126ddc934fe.png)

![image](https://user-images.githubusercontent.com/2511498/27112092-45c8795c-50e7-11e7-89a3-e10357d6ab5c.png)

**Comment by timmolter** [comment]
Radar chart done. V3.5.0.

**Comment by ningpp** [comment]
Thanks

**Comment by timmolter** [comment]
Thanks @hakantkn for implementing this!
