### ISSUE TITLE
Y-axis data in Histogram is not correct

### ISSUE THREAD

**Issue by Ananthareddyn4** [knowm/XChart#205]
i am trying to use Xchart for generating Histogram in java, i am using the below code

```
 Histogram histogram = new Histogram(myData, 3);
CategoryChart chart = new CategoryChartBuilder().width(800).height(600).title("Xchart Histogram").xAxisTitle("Mean").yAxisTitle("Count").build();
 chart.addSeries("histogram ", histogram.getxAxisData(), histogram.getyAxisData());

```

but the Y-axis data(that is, the frequency) is not the correct data(i am comparing wrt histogram chart generated in excel sheet using **frequency** formula)

**Comment by timmolter** [comment]
Please past a full working example class with a main method, and I'll take a look at it.

**Comment by Ananthareddyn4** [comment]
`public static void main(String[] args) throws IOException {
		
		List<Double> myData = new ArrayList<>();
		myData.add(10.0);
		myData.add(20.0);
		myData.add(10.0);
		myData.add(30.0);
		myData.add(40.0);
		myData.add(20.0);
		myData.add(30.0);
		myData.add(10.0);
		myData.add(40.0);
		myData.add(50.0);
		myData.add(10.0);
		myData.add(10.0);
		
		int numBins = 3;
		 Histogram histogram = new Histogram(myData, numBins);
		 CategoryChart chart = new CategoryChartBuilder().width(800).height(600).title("Xchart Histogram").xAxisTitle("Mean").yAxisTitle("Count").build();
		  chart.getStyler().setAvailableSpaceFill(.96);
		  chart.getStyler().setOverlapped(false);
		  chart.addSeries("histogram ", histogram.getxAxisData(), histogram.getyAxisData());
		  BitmapEncoder.saveBitmap(chart, "\\MyHistogram", BitmapFormat.JPG);
		  
		  System.out.println("Bins :"+histogram.getxAxisData());//Bins :[16.666666666666668, 30.000000000000004, 43.333333333333336]
		  System.out.println("frequency :"+histogram.getyAxisData());//frequency :[7.0, 2.0, 3.0]

	}`

**Comment by timmolter** [comment]
In the 16.67 bin the range is from between 10 and 23.26. Looking at the data there are 7 that fall in this range: 5x10 and 2x20, which is 7 total. I think XChart is correct.

**Comment by Mr14huashao** [comment]
@timmolter 
Results calculated on MATLAB:
![issue205](https://user-images.githubusercontent.com/57353473/77813218-d616ea80-70e1-11ea-8982-7ada551edccb.png)

**Comment by Mr14huashao** [comment]
@timmolter 
The caculated yData is not wrong, this is not a bug.
