### ISSUE TITLE
Step Chart Feature

### ISSUE THREAD

**Issue by bernard01** [knowm/XChart#211]
It could be nice to be able to draw steps like stairs in a line chart without interpolation between the points. Perhaps it is possible without change, then it would be nice to have an example.

**Comment by timmolter** [comment]
It's not yet possible. I'll eave this open as a feature request.

**Comment by bernard01** [comment]
Hi Tim,

I discovered that new feature series.setXYSeriesRenderStyle(XYSeries.XYSeriesRenderStyle.Step) which looks perfect to me. Many thanks. XChart is awesome!
