### ISSUE TITLE
Zoom, Pan

### ISSUE THREAD

**Issue by stolsvik** [knowm/XChart#216]
It would be **great** if there was an easy way to get a zoom and pan feature. For typically time-series data, you can have big data sets, and you want to zoom in and pan around in the data.

HighCharts has a quite simple variant of this: https://www.highcharts.com/demo/line-time-series - drag over the chart area to zoom. A button appears to reset the zoom.

For their "HighStocks" variant, there's also the the "navigator" at the bottom: https://www.highcharts.com/stock/demo/compare - here you can drag across the chart area to zoom, and notice how the navigator (the bottom "sparkline") also functions as a panning tool, if you take hold of the zoomed area and drag it.

Here's another way: https://www.amcharts.com/demos/line-chart-with-scroll-and-zoom/ - very similar to HighStocks, but here the mouse wheel also works.

A maybe simpler way is to allow for panning by simply taking hold of the chart with the mouse (drag) and enable zoom with scroll wheel. A reset-button would be great, though - like Highcharts has.

Even if X-zoom is implemented with dragging, it would still make some sense to be able to zoom the Y axis. An intuitive way for this is to use the scroll wheel.

**Comment by MoritzGoeckel** [comment]
I would love to see this feature!

**Comment by trigchen** [comment]
+1

**Comment by VanGoghDev** [comment]
2k19 and I still need this feature

**Comment by landret** [comment]
Very interested in this feature : X pan and X zoom. 
Just wanted to know when this would be implemented.

About the X zoom, this is a personal opinion but I think the simplest to use is the drag over the chart area to zoom plus reset button (like HighCharts). Mouse wheel could help too to zoom/unzoom around the area selected.

**Comment by landret** [comment]
I just saw this problem has been solved and commited month ago in the dev. That's great! When will the next XChart version 3.5.5 be released?

**Comment by timmolter** [comment]
OK, i pushed a new 3.6.0 jar.

**Comment by landret** [comment]
Thanks a lot @timmolter for the .jar. And also thanks to @hakantkn for his work on the zoom. I really appreciate this library and what you guys are doing.

I noticed the link to the .zip is not working (error 404) but the Maven link works.

**Comment by landret** [comment]
From what I saw, there are currently no example in the demo of how the new features implemented by @hakantkn works so I went through the test examples
TestForSelectionZoom.java
TestForCoordinateLookup.java
TestForCustomChartParts.java

I noticed one thing about the Selection Zoom. If a zoom has been done, and if once again an area selection is performed but with no data inside, "reset button" disappears while it should not.

**Comment by timmolter** [comment]
thanks, the link works now.

**Comment by phraktle** [comment]
@timmolter FYI, the 3.6.0 download link is broken on the XChart homepage.

**Comment by timmolter** [comment]
weird, maybe it's a caching issue. I cleared the cache. Could you try now?

**Comment by hakantkn** [comment]
> I noticed one thing about the Selection Zoom. If a zoom has been done, and if once again an area selection is performed but with no data inside, "reset button" disappears while it should not.

See #357

**Comment by timmolter** [comment]
This will be coming out in the next release! Thanks, @Mr14huashao and @hakantkn !
