### ISSUE TITLE
SteppedBar plots everything as Scatter when set via getStyler().setDefaultSeriesRenderStyle

### ISSUE THREAD

**Issue by hypirion** [knowm/XChart#226]
When using

```java
chart.getStyler().setDefaultSeriesRenderStyle(CategorySeriesRenderStyle.SteppedBar);
```

The chart is plotted as if the default render style is Scatter. For a minimal reproducible case (`Repro.java`):

```java
import java.util.Arrays;

import org.knowm.xchart.BitmapEncoder;
import org.knowm.xchart.CategoryChart;
import org.knowm.xchart.CategoryChartBuilder;
import org.knowm.xchart.CategorySeries;
import org.knowm.xchart.CategorySeries.CategorySeriesRenderStyle;

public class Repro {
    public static void main(String[] args) throws Exception {
        CategoryChart chart = new CategoryChartBuilder().width(600).height(450).title("Temperature vs. Color").xAxisTitle("Color").yAxisTitle("Temperature").build();

        CategorySeries[] categorySeries = new CategorySeries[2];
        categorySeries[0] = chart.addSeries("fish", Arrays.asList("Blue", "Red", "Green", "Yellow", "Orange"), Arrays.asList(40, 30, 20, 60, 60));
        categorySeries[1] = chart.addSeries("worms", Arrays.asList("Blue", "Red", "Green", "Yellow", "Orange"), Arrays.asList(50, 10, -20, 40, 60));

        chart.getStyler().setDefaultSeriesRenderStyle(CategorySeriesRenderStyle.SteppedBar);

        BitmapEncoder.saveBitmap(chart, "out.png", BitmapEncoder.BitmapFormat.PNG);
    }
}
```

Compile with `javac -cp xchart-3.5.0.jar Repro.java` and `java -cp xchart-3.5.0.jar:. Repro`, assuming you have `xchart-3.5.0.jar` in the same directory. This will emit a PNG image which looks like this:

![out](https://user-images.githubusercontent.com/504876/31576114-0e2150b4-b0f5-11e7-995e-c63201f6ac83.png)

Replacing the default styler call with calls to manually set SteppedBar works fine, however:

```java
categorySeries[0].setChartCategorySeriesRenderStyle(CategorySeriesRenderStyle.SteppedBar);
categorySeries[1].setChartCategorySeriesRenderStyle(CategorySeriesRenderStyle.SteppedBar);
```

![out-ok](https://user-images.githubusercontent.com/504876/31576139-48bc1e98-b0f5-11e7-8e17-75a78089e4b0.png)

This was tested on XChart 3.5.0.

----

EDIT: There are also some strange interactions between the default render style and manual render styles as well. This will also just print in the Scatter style:

```java
chart.getStyler().setDefaultSeriesRenderStyle(CategorySeriesRenderStyle.SteppedBar);
categorySeries[0].setChartCategorySeriesRenderStyle(CategorySeriesRenderStyle.SteppedBar);
categorySeries[1].setChartCategorySeriesRenderStyle(CategorySeriesRenderStyle.SteppedBar);
```

**Comment by hypirion** [comment]
After some digging, this seems to be an issue with other styles as well. If we use the same code as above and want to print one Scatter and one Bar series, we end up with an ok result here:

```java
chart.getStyler().setDefaultSeriesRenderStyle(CategorySeriesRenderStyle.Bar);
categorySeries[0].setChartCategorySeriesRenderStyle(CategorySeriesRenderStyle.Scatter);
```

![out-ok](https://user-images.githubusercontent.com/504876/31576188-460930fe-b0f6-11e7-9602-5dde8cfc0264.png)

However, if we invert the logic, like so (They should be equivalent):

```java
categorySeries[1].setChartCategorySeriesRenderStyle(CategorySeriesRenderStyle.Bar);
chart.getStyler().setDefaultSeriesRenderStyle(CategorySeriesRenderStyle.Scatter);
```

We end up with the same issue as mentioned above:

![out-ok](https://user-images.githubusercontent.com/504876/31576202-7365aaaa-b0f6-11e7-8bce-7681005d3c10.png)

**Comment by timmolter** [comment]
Thanks I'll fix it soon hopefully...

**Comment by Mr14huashao** [comment]
Hey @timmolter 
Currently I'm looking into this issue.
I digged into the code and find the code in class `Plot_Category` like this:
```
    if (CategorySeriesRenderStyle.Bar.equals(stylerCategory.getDefaultSeriesRenderStyle())
        || CategorySeriesRenderStyle.Stick.equals(stylerCategory.getDefaultSeriesRenderStyle())) {
      this.plotContent = new PlotContent_Category_Bar<ST, S>(chart);
    } else {
      this.plotContent = new PlotContent_Category_Line_Area_Scatter<ST, S>(chart);
    }
```
It seems that if `chart.getStyler().setDefaultSeriesRenderStyle(CategorySeriesRenderStyle.SteppedBar);`  was called, the `defaultSeriesRenderStyle` would be set to `SteppedBar`, and the code in `Plot_Category` would process the painting job using `PlotContent_Category_Line_Area_Scatter` here.

Some questions:
1. Should we change the code in `Plot_Category` to let `PlotContent_Category_Bar` do the painting job when drawing `SteppedBar`? Is this enough? Sample code here:
```
    if (CategorySeriesRenderStyle.Bar.equals(stylerCategory.getDefaultSeriesRenderStyle())
        || CategorySeriesRenderStyle.Stick.equals(stylerCategory.getDefaultSeriesRenderStyle())
        || CategorySeriesRenderStyle.SteppedBar.equals(stylerCategory.getDefaultSeriesRenderStyle())) {
      this.plotContent = new PlotContent_Category_Bar<ST, S>(chart);
    }
```
2. Actually I have no idea what `SteppedBar` should be look like as it's only used here. Is `PlotContent_Category_Bar` working correctly on painting `SteppedBar`? If not, should we add a new class like `PlotContent_Category_SteppedBar` to do the job?
