### ISSUE TITLE
Lines on ohlc candles?

### ISSUE THREAD

**Issue by IanWorthington** [knowm/XChart#250]
I'm trying to draw a chart which includes lines and ohlc candles.  Is this possible?

**Comment by timmolter** [comment]
Yes, see the `README`.

**Comment by IanWorthington** [comment]
Sorry Tim, but I'm not seeing this.

According to your readme I need an OHLCChart/OHLCChartBuilder to draw a chart of candles and an XYChart/XYChartBuilder to draw a chart of lines.

I can't see anything about how to draw both on the same chart.

**Comment by timmolter** [comment]
Oh, sorry, I misread you. No, that's not possible right now. I'll reopen this as a feature request.

**Comment by IanWorthington** [comment]
Thanks Tim.  Being able to add lines to ohlc charts is fairly important I think.

**Comment by ajdevy** [comment]
Very important indeed, also would like to draw lines on Bar(Histogram) charts, @timmolter maybe you can point to the direction where and how this can be implemented, maybe I can create a pull request if that's not too difficult to handle

**Comment by neramirez** [comment]
yeah, very important, probably something to merge two different types of charts?

**Comment by hohl** [comment]
Yes, I'd like to see that feature too.

**Comment by vipulnewaskar7** [comment]
Hello, I am new to github and hence Xchart,
But I have some "abstract" solution for this...
Please correct me if I am wrong...
This is similar to the feature "donut with multiple rings"
Here there are more than one series, so
There should be "array" of Series.
Series should be plotted on same "Theme". 
e.g. plot series1 of type "OHLC" on theme and 
then plot series 2 of type "line" on same theme.
For histogram also, we can use similar technique.
