### ISSUE TITLE
The distance between Y axis and chart randomly changes.

### ISSUE THREAD

**Issue by ejabarov** [knowm/XChart#257]
I am creating chart and writing them to pdf file. However when I create chart the distance between chart and Y axis not always appears the same (in most cases that distance is quite big). 1 time out of 10 times the distance works fine as you see from the pics
![ver](https://user-images.githubusercontent.com/9068537/38350224-5783d722-38e5-11e8-8dde-ea75c97acd5e.JPG)
![ver1](https://user-images.githubusercontent.com/9068537/38350225-57ad096c-38e5-11e8-9eb5-a895c28766fa.JPG)

However if I display the chart using new SwingWrapper<CategoryChart>(chart).displayChart() and if the  distance between Yaxis and chart is large and I resize the window it automatically adjust the distance between chart and Y axis. Any idea why it happens so? Thank you in advance

**Comment by timmolter** [comment]
Seems like a bug. If you can give me source code for a sample chart demonstrating the bug, I'll investigate and fix it.

**Comment by ejabarov** [comment]
`public class VerBarChartCreate {


	public static ProcessingPipeline create() throws SQLException, NumberFormatException, IOException, AWTException {

		CategoryChart chart =
		        new CategoryChartBuilder()
		            .width(500)
		            .height(500)
		            .title("Average Weight and Height per Team")
		            .xAxisTitle("Team_ID")
		            .build();
		    // Customize Chart

		    chart.getStyler().setPlotGridVerticalLinesVisible(false);
		    chart.getStyler().setStacked(true);
		    chart.getStyler().setPlotGridHorizontalLinesVisible(true);   
		    chart.getStyler().setLegendPosition(LegendPosition.OutsideS);
		    chart.getStyler().setLegendLayout(LegendLayout.Horizontal);
		    List<String> category_values = new ArrayList<String>(); 
		   
		    
		    for(int i = 1; i<=15; i++) {
		    	category_values.add("K0" + i);
		    }
		   
		    List<Double> height = new ArrayList<Double>(); 
		    
		    List<Double> weight = new ArrayList<Double>(); 
		  
		    for(int i = 1; i<=15; i++) {
		    	weight.add((double) (i+45));
		    	height.add((double) (i+30));
		    }
		    
		   chart.addSeries("Average_Height",category_values,height);
		   chart.addSeries("Average_Weight",category_values,weight);
		   
		    new SwingWrapper<CategoryChart>(chart).displayChart();
	        ProcessingPipeline g = null;
			g = new PDFGraphics2D(0, 0, chart.getWidth(), chart.getHeight());
			chart.paint(g, chart.getWidth(), chart.getHeight());


			
			return g;
	}

}`
Here is the source. Try to run it few times. Thank you

**Comment by ejabarov90** [comment]
any idea why it happens so?

**Comment by timmolter** [comment]
I made a test class with your code (https://github.com/knowm/XChart/commit/8932ccc6c01687821b6aff157328f53f653d5f3e), but I cannot reproduce your issue.

**Comment by ejabarov** [comment]
I see. It appears that writing chart do pdf without displaying chart does not cause that problem. Thank you

**Comment by timmolter** [comment]
It takes a few seconds for the PDF to be generated so it you also have a Swing window showing the same chart and it's being resized, unexpected results for the PDF chart can probably be expected.
