### ISSUE TITLE
Unicode

### ISSUE THREAD

**Issue by ejabarov** [knowm/XChart#260]
Hello,

It would be great to add Unicode so that we can display Korean characters as well. I checked it works well with Chinese and Japanese characters but now with Korean.  
Currently if I want to set the chart title "안녕하세요!" it shows them as a squares.

Thank you.

**Comment by timmolter** [comment]
If you can make a sample test class, I can try to get it to work out.

**Comment by ejabarov** [comment]
`
public class Stacked  {
	  public static void main(String[] args) {
		  
		  CategoryChart chart = getChart();
		    new SwingWrapper<CategoryChart>(chart).displayChart();
		  }
		 

		  public static CategoryChart getChart() {
		 
			  CategoryChart chart =
				        new CategoryChartBuilder()
				            .width(500)
				            .height(500)
				            .title("안녕하세요!")
				            .xAxisTitle("팀 ID")
				            .yAxisTitle("이름" )
				            .build();

				    chart.getStyler().setPlotGridVerticalLinesVisible(false);
				    chart.getStyler().setStacked(true);
				    chart.getStyler().setPlotGridHorizontalLinesVisible(true);   
				    chart.getStyler().setLegendPosition(LegendPosition.OutsideS);
				    chart.getStyler().setLegendLayout(LegendLayout.Horizontal);
				    List<String> category_values = new ArrayList<String>(); 
				   
				    
				    for(int i = 1; i<=15; i++) {
				    	category_values.add("키0 " + i);
				    }
				   
				    List<Double> height = new ArrayList<Double>(); 
				    
				    List<Double> weight = new ArrayList<Double>(); 
				  
				    for(int i = 1; i<=15; i++) {
				    	weight.add((double) (i+45));
				    	height.add((double) (i+30));
				    }
				    
				   chart.addSeries("시리즈 1",category_values,height);
				   chart.addSeries("시리즈 2",category_values,weight);

					return chart;

		  }
}
`

**Comment by ejabarov** [comment]
Thank you for your response. The problem is related with font. If I change the font as follows it also works fine. 
`
   chart.getStyler().setChartTitleFont(new Font("Malgun Gothic", Font.PLAIN, 12 ));
   chart.getStyler().setAnnotationsFont(new Font("Malgun Gothic", Font.PLAIN, 12 ));
   chart.getStyler().setToolTipFont(new Font("Malgun Gothic", Font.PLAIN, 12 ));
   chart.getStyler().setAxisTickLabelsFont(new Font("Malgun Gothic", Font.PLAIN, 12 ));
   chart.getStyler().setAxisTitleFont(new Font("Malgun Gothic", Font.PLAIN, 12 ));
   chart.getStyler().setBaseFont(new Font("Malgun Gothic", Font.PLAIN, 12 ));
   chart.getStyler().setLegendFont(new Font("Malgun Gothic", Font.PLAIN, 12 ));
`

Thank you

**Comment by timmolter** [comment]
Well, it seems like it's definitely font issue, which is inconsistent across different OSs.
