### ISSUE TITLE
The font 'Dialog.plain' contains a bad /BBox

### ISSUE THREAD

**Issue by ejabarov** [knowm/XChart#261]
Hello, 

When I write the chart to pdf using the following:

`VectorGraphicsEncoder.saveVectorGraphic(chart, "./Sample_Chart", VectorGraphicsFormat.PDF);`

and open the .pdf file using the Acrobat Reader the warning pops up. 

Any idea how to fix or not to show that warning?

![capture](https://user-images.githubusercontent.com/9068537/39033300-58bc82ce-44ac-11e8-89ba-3874e20c1ad9.JPG)

**Comment by timmolter** [comment]
Sorry, I never ran into that issue. Can you try the latest XChart snapshot jar? I updated the vectorgraphics2d dependency. Maybe it contains a fix for it!?!

https://oss.sonatype.org/content/repositories/snapshots/org/knowm/xchart/xchart/3.5.2-SNAPSHOT/

**Comment by ejabarov** [comment]
I tried with the latest jar but it gives the following error: 
`
Exception in thread "main" java.lang.NoSuchMethodError: de.erichseifert.vectorgraphics2d.VectorGraphics2D.getCommands()Lde/erichseifert/vectorgraphics2d/intermediate/CommandSequence;
	at org.knowm.xchart.VectorGraphicsEncoder.saveVectorGraphic(VectorGraphicsEncoder.java:48)
	at Stacked.main(Stacked.java:27)

`
BTW I am using the example code called "Save Chart as Bitmap".

Thank you

**Comment by timmolter** [comment]
You also have to update the `vectorgraphics2d` dependency to 0.13 i believe

**Comment by mtrevisan** [comment]
I have the very same problem.
Moreover, using java, I embedded the XChartPanel created from the chart into a JTabbedPane. When I save an image all goes fine. But whenever I choose pdf it creates an empty pdf, and only when I close my JPanel that contains the JTabbelPane the file will actually be written.
However when I open it Acrobat says me that "The font 'Dialog.plain' contains a bad /BBox".
I'm using the latest version, 3.5.2, of XChart.

**Comment by Mr14huashao** [comment]
Adobe Reader software version 11.0.00, open pdf file error, online said to upgrade, this I did not try;

But try other ways, open with other software or browser, it is normal.

So this is not an XChart problem.

**Comment by timmolter** [comment]
In the next release (coming soon) we're using a different PDF renderer so hopefully this issue will just disappear.
