### ISSUE TITLE
Font change

### ISSUE THREAD

**Issue by SuperMarcomen** [knowm/XChart#262]
Hi, how can I change only this font here?
http://prntscr.com/j80zis

**Comment by ejabarov** [comment]
I hope the following helps:

`
protected final static Font fontFace = new Font(fontPath, Font.PLAIN, 12 );
chart.getStyler().setAnnotationsFont(FontFace);

`

**Comment by timmolter** [comment]
![download](https://user-images.githubusercontent.com/738972/71508856-7e21db00-2889-11ea-88ca-6803e739ec58.png)

**Comment by SuperMarcomen** [comment]
Thanks, it solved the problem
