### ISSUE TITLE
DateFormatter with dynamic format

### ISSUE THREAD

**Issue by MartyIX** [knowm/XChart#265]
Hi,

we have an old script in Python generating charts powered by Matplotlib. I'm trying to migrate to Java-only codebase to get rid of Python.

One thing that I'm having trouble with is to create a chart with the following x-axis labels:

![screenshot from 2018-04-25 15-52-26](https://user-images.githubusercontent.com/203266/39250261-c0447a44-48a0-11e8-8f3d-06075cea02c6.png)

I don't think I can achieve the similar result with the current version of XChart. Am I correct?

Maybe I can create PR for this feature. It looks like `AxisTickCalculator_Date` is the class to start investigating how to add the functionality, right?

Best regards,
Martin

**Comment by hakantkn** [comment]
You can use custom axis tick calculator. See #217
