### ISSUE TITLE
Line chart with String X-Axis data, starting closer to Y-Axis

### ISSUE THREAD

**Issue by cos64** [knowm/XChart#267]
I'm trying to make a line chart with String values in the X-Axis.
`XYChart` doesn't work because _"Series data must be either Number or Date type"_ (as an exception message told me).
So I tried to use a `CategoryChart` with line rendering (as in your [example](https://github.com/knowm/XChart/blob/develop/xchart-demo/src/main/java/org/knowm/xchart/demo/charts/line/LineChart07.java)).
This way it works, but the offset of the line's starting point is a bit too large for my taste.
This is how it looks:
![actual](https://user-images.githubusercontent.com/16708031/40443339-b00c2f66-5ece-11e8-8c56-b1f0f3d3958c.png)
And this is what I'd like:
![expected](https://user-images.githubusercontent.com/16708031/40443341-b03386a6-5ece-11e8-8ece-7236e77fbbbf.png)
I checked the API and also did some debugging, and there seems to be no way to configure this.
I found the `xOffset` variable in:
`org.knowm.xchart.internal.chartpart.PlotContent_Category_Line_Area_Scatter.doPaint(Graphics2D)`
As far as I can tell, we always add half a `gridStep` at the beginning.

If you don't have time for that, I would try to change this myself and then send a pull request, but I'd like your opinion.

1) Should we try and alter the aforementioned part of the code (`PlotContent_Category_Line_Area_Scatter`)? Maybe that half `gridStep` makes sense for bar charts, but for lines maybe it could be different.
2) Should we change the `XYChart` to accept Strings for the X-Axis? I'm thinking of using the index of the String array for the values, and the actual String only as a label.

Which variant makes more sense to you?

Or do you see another way of doing it?

**Comment by timmolter** [comment]
Option one would be better. You could make it a configurable style parameter.

**Comment by hakantkn** [comment]
You can use custom axis tick calculator.
Here is an example:
```
    List<Integer> xData = new ArrayList<Integer>();
    List<Double> yData = new ArrayList<Double>();
    xData.add(1);
    xData.add(2);
    yData.add(50.0);
    yData.add(49.9995);
    
    // Create Chart
    XYChart chart =
        new XYChartBuilder()
            .width(800)
            .height(600)
            .title("Test")
            .xAxisTitle("Power")
            .yAxisTitle("Value")
            .build();

    // Customize Chart
    chart.getStyler().setChartTitleVisible(true);
    chart.getStyler().setLegendVisible(false);
    
    chart.getStyler().setXAxisLabelRotation(45);


    // Series
    chart.addSeries("10^x", xData, yData);

    Map<Double, Object> xMarkMap = new TreeMap<Double, Object>();
    xMarkMap.put(1.0, "initial value");
    xMarkMap.put(2.0, "2016-01");

    chart.setXAxisLabelOverrideMap(xMarkMap);

```
Here is the screenshot:

![image](https://user-images.githubusercontent.com/6737748/40482690-44cc241e-5f5e-11e8-9e7c-550edb6b6304.png)
