### ISSUE TITLE
Custom text at data points

### ISSUE THREAD

**Issue by Narvaris** [knowm/XChart#270]
Hi,

I was wondering if it is possible to add custom text at each data point, resulting in a chart similar to that shown below:
![image](https://user-images.githubusercontent.com/39590308/41645661-e4933f6e-7471-11e8-8db3-29bdb318ba33.png)

**Comment by spidru** [comment]
This is in fact what I had proposed in #227

**Comment by hakantkn** [comment]
This is added at the latest commit.
To set custom tooltips use `series.setToolTips()`.
To make them always visible use `chart.getStyler().setToolTipsAlwaysVisible(true);`

**Comment by BpArCuCTeMbI** [comment]
Hello, @hakantkn ! isn't this feature in the latest (3.5.2) release? Should I compile the library from sources to get the custom labels feature working?
![ss 2018-12-01 at 09 13 02](https://user-images.githubusercontent.com/4931448/49331439-feeea480-f5ad-11e8-8503-8008f4f95536.png)

**Comment by hakantkn** [comment]
@BpArCuCTeMbI This feature is implemented after 3.5.2.
So you need to compile library from sources.

**Comment by BpArCuCTeMbI** [comment]
@hakantkn thank you. But I have a problem with my program - I have a `XYchart` with one series added by `addSeries` method. It's already existing on the user's screen. When the user pushes the button, i need to change the current XYchart:
1)Add new series to it with `chart.addSeries` (it's working for me)
2) For this second series I need  to enumerate the points (1, 2, 3, 4... etc) with custom ToolTips.
I'm trying to do that on the screenshot in `plotConvex` method:
![ss 2018-12-02 at 06 10 08](https://user-images.githubusercontent.com/4931448/49341366-86dfb780-f65d-11e8-89e1-a56b2876ec05.png)

For now it shows the coordinates of all points from the first and second series and also it shows my enumeration (1, 2, 3, 4... etc) for the second series. I'd like to have only enumeration for the second series. Could you help me with that?
![ss 2018-12-02 at 06 15 39](https://user-images.githubusercontent.com/4931448/49341448-8398fb80-f65e-11e8-85f3-e044b9fa54ac.png)

**Comment by hakantkn** [comment]
I guess you set tooltips for series 1 and want to remove them when adding series 2.
If I remember correctly you need to update series 1 tooltips to null (maybe an array of nulls for each point ie {null, null, ...}.

**Comment by timmolter** [comment]
Setting the tooltips to null is kind of a hack. We should update the code to handle this automatically.

**Comment by hakantkn** [comment]
> Setting the tooltips to null is kind of a hack. We should update the code to handle this automatically.

Currently there is no way to disable tooltips per series. Only working hack right now is adding a string[] of null's.

An alternative might be moving `chart.getStyler().isToolTipsEnabled()` to `series.isToolTipsEnabled()`.
