### ISSUE TITLE
Problem with output when rendering the chart in SVG or PDF

### ISSUE THREAD

**Issue by andri-anski** [knowm/XChart#271]
When rendering the charts to PDF or SVG, the x-axis shifts, so the y-values are not plotted over the x-values. The output via swing is correct.

I use Maven. The version is 3.5.2.
The VectorGraphics2D library has version 0.13.

Thank you for support!

![chart](https://user-images.githubusercontent.com/16418156/41797859-e05a9a0e-766b-11e8-9361-d8544272fc19.JPG)

**Comment by timmolter** [comment]
Thanks for letting me know.

**Comment by Mr14huashao** [comment]
@timmolter 
Now verify that there is no such problem, has it been resolved?

**Comment by timmolter** [comment]
Can you test it please? If it's fixed, I can close this issue.

**Comment by Mr14huashao** [comment]
display chart:
![Screenshot_2019-12-23_11-04-59](https://user-images.githubusercontent.com/57353473/71333196-165f4d80-2574-11ea-93db-e94227c55a5c.png)

save as SVG:
![Screenshot_2019-12-23_11-07-16](https://user-images.githubusercontent.com/57353473/71333274-6a6a3200-2574-11ea-9346-dae36b8c5c6a.png)

save as PDF:
![Screenshot_2019-12-23_11-09-27](https://user-images.githubusercontent.com/57353473/71333376-b5844500-2574-11ea-9a4a-c0be022c7cf5.png)

No problem as @andri-anski said.

**Comment by Mr14huashao** [comment]
@timmolter 
This bug cannot be reproduced.

Save the PDF file, the same as the original image, and the implementation method is different from the previous.
Saving SVG files may sometimes be slightly different from the original image, but it is not a problem.
