### ISSUE TITLE
Realtime XY Chart Memory Issues

### ISSUE THREAD

**Issue by jasonumcp** [knowm/XChart#274]
I'm working on a project using an XYChart for realtime charting.  I found the chart easy to configure and integrate into my existing application.  I am reading in data from my server and attempting to redraw the chart every 75 milliseconds or so.   For background, I am running 32-bit Java 6 (due to requirements) on Windows 7.  

Now that the integration is done I let it run over the weekend.  I left 8 separate JVMs running individual instances (each with a different data source) of my charting application.  After about 4 days  of running, when I checked Monday morning I found that my server had crashed throwing "java.lang.OutOfMemoryError: unable to create new native thread" and many other errors.  When I looked at the Windows task manager, it reported that each of my JVMs was using 1.1 GBs of memory which ate up almost all of the memory on the computer.  However, when I looked at JConsole, it showed my Heap was very happy running around 64MB.  I saw no runaway threads, excessive class loading, CPU, or heap memory usage.  Nothing remotely close to the 1.1 GB I saw reported by Windows task manager.

I've spent the last few days trying to isolate and narrow the problem down using JConsole, JVisualVM, and SysInternals.  I was able to finally, I believe, narrow it down to something in the XChart library but don't yet know the cause.

I took the SimpleRealTime example in the org.knowm.xchart.standalone.readme package and I believe I was able to recreate the memory growth.  The only change I made was to change the Thread.sleep(100) call to be Thread.sleep(25) to trigger the problem quicker.  This morning, after running this standalone example (again Java 6 32-bit on Windows 7) for almost 5 hours, the Heap was running nicely in the 10MB range.  However, Windows reported that the javaw process was using over 500 MB of memory.  During that time we even forced a full garbage collect and while the heap went down, the memory in Windows task manager kept slowly increasing.  I stopped it to do some other tests but am going to try and leave it running overnight tonight.

So I guess my question is, do you know of any memory issues using the XY Chart for realtime?  Am I just pushing the chart redraws too quickly causing some other issue?  Even when I was doing 100 ms between iterations on my app, I saw the memory grow although not as quickly.  

I did a similar program 8 or so years ago with JFreeChart and no one was thrilled with the performance at that time.  It is one of the reasons I went looking for another charting package for this project.  I don't want to switch this over to that, but asking the users to restart the app every few days isn't going to go over too well.

One thing I noticed that is probably not an issue but I figured I would mention anyway is that while using SysInternals Process Monitor, I see there are a number of reads of the Font files for every redraw.  So the Process Monitor fills up with (in my case) thousands of reads of C:\Windows\Font\arialbd.ttf.  After just under 2 hours I have over 100,000 TTF file reads (it appears to be increasing a few hundred a second).  Again, I don't know if it is related and I've never tracked this in other apps I've done but it seemed like a lot of Font file reads for every single redraw.

Thank you in advance for your help, sorry for the long-winded explanation, and let me know if you have any followup questions.

**Comment by timmolter** [comment]
I appreciate your explanation, so thanks for bringing the issue to light. I'll try running it here on my Mac under Oracle jre8 and see if I also experience the same thing. I really don't have any ideas at this point regarding memory issues. The font thing seems suspicious though. Did you try googling about that issue? Maybe it's an issue that has come up before in other contexts.
I'll post an update after my experiment.

**Comment by jasonumcp** [comment]
Tim, thank you for the response.  I left a number of tests going last night with interesting results:

On an older 32 bit XP machine, using 32 bit Java 6 I ran my application with only one chart open.  After 1 day and 15 hours it is stead at 81 MB (shown in the Windows Task Manager).  I added a 2nd chart and 3 hours later the first chart is still at 81 MB and the second one is at 77 MB.  I can't open many more as the computer itself has an old slow CPU and 2 GB of RAM so I can't do the full 8 window test on it.

On a different 64 Bit Windows 7 machine (a clone of the one my original test is on) I ran a test using the  SwingWorkerRealTime demo.  After 16 hours it was around 343 MB.  At the same time, on this machine, I ran my sped up (25 ms sleep) SimpleRealTime demo test.  After 16 hours task manager reported the process was using 1.5GB of memory.  This was also running 32 bit Java 6.  So this confirms what I originally saw a few days ago.

On my original test 64 Bit Windows 7 machine, I also ran my sped up SimpleRealTime demo test.  However, this time I ran it using 32-bit Java 8.  After running for 20 hours, the Task Manager reported the memory is at 124 MB.  I actually came in this morning and it was at 130 MB but at some point I'm assuming some garbage collection occurred and it went down.  This is the first time I've seen a process give memory back to the computer while running these tests.  The only thing I added to try and test was the "-XX:NativeMemoryTracking=summary" flag.  I don't think that should affect it but I was trying to see if there was any leak.  I guess I may try restarting this test without the flag to see if it has any affect.

I ran the process monitor check on the SimpleRealTime demo running under Java 8 and still saw a crazy number of font file reads, but apparently it doesn't affect the memory at this point.  So I'm not sure if the problem is related or if it is the file reads being handled better in 8.

I'll try and keep doing some testing today and let you know if I find more.  I wanted to get these updates to you.

Thank you again for your help.

**Comment by Mr14huashao** [comment]
@timmolter 
SimpleRealTime class, refreshed every 1 millisecond.
After running for a day, the memory grows slowly. The current memory usage is 168M.

**Comment by timmolter** [comment]
Looks like a memory leak somewhere. Did you ever use VisualVM? https://docs.oracle.com/javase/8/docs/technotes/guides/visualvm/profiler.html
You can use it to see what objects are growing in size. Maybe the culprit can be found. It could be that a bunch of Lists are getting created and never getting garbage collected.

**Comment by Mr14huashao** [comment]
Profiling results:
![image](https://user-images.githubusercontent.com/57353473/76919478-043b4400-6904-11ea-8e0a-27e891cfa635.png)

**Comment by Mr14huashao** [comment]
@timmolter 
Use VisualVM memory analysis, click on the memory analysis several times, the program memory grows to 947.7M, shut down VisualVM, after 3 hours the program memory grows to 947.8M, only 0.1M.

**Comment by timmolter** [comment]
I'm getting around 150 MB and so far nice garbage collection and stability. I'll let it run for a good 24 hours.

![Screen Shot 2020-03-18 at 09 22 20](https://user-images.githubusercontent.com/738972/76940171-0698a080-68fa-11ea-806f-e013963febc7.png)

**Comment by Mr14huashao** [comment]
Before using the profiler memory analysis, the memory usage on my side is similar to your current one.

**Comment by timmolter** [comment]
After 24 hrs, there is no memory leak that I can see. Although if I look at Activity Monitor it's over 400 MB. Am I looking at the right stuff??

![Screen Shot 2020-03-19 at 10 32 12](https://user-images.githubusercontent.com/738972/77052325-f30a3a00-69cc-11ea-8c34-22e16152c488.png)

![Screen Shot 2020-03-19 at 10 32 24](https://user-images.githubusercontent.com/738972/77052320-f1407680-69cc-11ea-90b4-485a6ae8f1db.png)

<img width="798" alt="Screen Shot 2020-03-19 at 10 34 54" src="https://user-images.githubusercontent.com/738972/77052627-6613b080-69cd-11ea-83a4-51dc21bd2154.png">

**Comment by Mr14huashao** [comment]
@timmolter 
The effect of my test is similar, I can't see where a memory leak occurs.

**Comment by timmolter** [comment]
477 MB today on Activity Monitor. It's running stable for me. I think maybe different JVMs and operating systems will have different results.

**Comment by timmolter** [comment]
I would recommend updating your JVM to at least Java 8, preferably Java 11.
