### ISSUE TITLE
Date axis labeling with timezone?

### ISSUE THREAD

**Issue by spyhunter99** [knowm/XChart#279]
Is there any way to force the rendering of axis labeling for java.util.Date objects to format to a specific time zone? Looks like it always renders to the users/systems current time zone.

**Comment by timmolter** [comment]
I don't think so.

**Comment by Mr14huashao** [comment]
@timmolter 
Found that the `AxesChartStyler` class has added properties `locale` and `timezone`.
I feel this feature has been implemented.
