### ISSUE TITLE
xychart.addSeries hanging with larger data sets

### ISSUE THREAD

**Issue by spyhunter99** [knowm/XChart#280]
I'm attempting to about 3 series, each with about 500k points.  The addseries method appears to be hanging.  Anything I can do to make it faster? Any known limits?

**Comment by spyhunter99** [comment]
Figured it out.  The utils class uses a for loop,  however I provided a linked list which made it very slow.  Consider using and iterator in the future

**Comment by timmolter** [comment]
would iterator make it faster?

**Comment by spyhunter99** [comment]
absolutely

**Comment by Mr14huashao** [comment]
The test found to be very slow
List.size() = 100000 takes 12 seconds, 5 million needs to wait a long time.
Test code:
```java
List<Integer> list = new LinkedList<>();
for (int i = 0; i < 100000; i++) {
	list.add(i);
}

long  t1 = System.currentTimeMillis();
Utils.getDoubleArrayFromNumberList(list);
long  t2 = System.currentTimeMillis();
System.out.println(t2 - t1);
```
LinkedList.get(index) is starting from 0 to index. It really needs to be changed to Iterator. Iterator has a lot of speed improvement, traversing 5 million data, and it takes less than 100 milliseconds.
