### ISSUE TITLE
Set line stroke for individual series

### ISSUE THREAD

**Issue by ChadShenk** [knowm/XChart#282]
A feature that would be very useful would be to set the type of line (solid, dotted, dashed, ect.) when adding a series. I use XChart without the markers enabled, as I only need the line to be visible. Declaring the line style would be useful for visualizing estimated data in a chart. Something such as addSeries(name, seriesData).setSeriesStroke(dashed);

**Comment by Mr14huashao** [comment]
I think it has this feature. Maybe you can see `/ xchart-demo / src / main / java / org / knowm / xchart / demo / charts / line / LineChart05.java`
It can work like this
`series.setLineStyle(SeriesLines.DASH_DASH);`
It also has other line styles, see `/ xchart / src / main / java / org / knowm / xchart / style / lines / SeriesLines.java`

**Comment by timmolter** [comment]
Yes, this is definitely already possible. Thanks, @Mr14huashao .
