### ISSUE TITLE
Is there an install guide?

### ISSUE THREAD

**Issue by jdaniel87** [knowm/XChart#283]
Hey Tim.  I really hate to ask...
Very interested in xcharts, as a high school teacher with BlueJ.
I have the jar loaded in my classpath, and your Example0
but cannot get the correct import statements
to recognize  XYChart or QuickChart or SwingWrapper

Sorry I am a novice and I do not know anything about Maven
Rest assured if I can get it running there will SOON be 53 new high school users of xcharts.

**Comment by timmolter** [comment]
Hi, I'm not familiar with BlueJ. However, my guess is that it's NOT on the classpath otherwise thoese classes should be recognized. Try googling the issue in general for BlueJ.

**Comment by jdaniel87** [comment]
will do,
I found the jar command to look at the manifest and I see my imports were
correct.
clearly a bluej issue.
 thanks kindly, Tim!
