### ISSUE TITLE
AnnotationType don`t change in PieChart when use a custom Theme

### ISSUE THREAD

**Issue by hariton594** [knowm/XChart#284]
My be must change [PieStyler.setTheme](https://github.com/knowm/XChart/blob/develop/xchart/src/main/java/org/knowm/xchart/style/PieStyler.java#L210) and add ```this.setAllStyles()``` ?

**Comment by Mr14huashao** [comment]
@hariton594 
`chart.getStyler().setTheme()` is placed in front of all styles.

`chart.getStyler().setTheme()` resets the theme's default style.

@timmolter 
This issue should not be a problem and can be closed.
