### ISSUE TITLE
saving multiple charts to a single pdf

### ISSUE THREAD

**Issue by macrinalobo** [knowm/XChart#285]
Is it possible to save 
ArrayList<XYChart>(numCharts) to a single pdf (or even jpeg) ? Maybe this could be added or could someone  point me in the direction of how this could be done ?  Thanks a lot.

**Comment by timmolter** [comment]
It exists for bitmaps (`BitmapEncoder.java`), but not yet PDFs ( `VectorGraphicsEncoder.java`).

**Comment by Mr14huashao** [comment]
```java 
// Found that this method is very slow to execute
VectorGraphicsEncoder.saveVectorGraphic(chart, "./Sample_Chart", VectorGraphicsFormat.PDF);
```

Add dependency
```xml
<dependency>
  <groupId>com.lowagie</groupId>
  <artifactId>itext</artifactId>
  <version>4.2.1</version>
</dependency>
```
```java
public static void testCreatePdf() {
    List<Chart> charts = new ArrayList<>();
    charts.add(new AreaChart01().getChart());
    charts.add(new BarChart01().getChart());
    charts.add(new LineChart01().getChart());
    charts.add(new PieChart01().getChart());
    charts.add(new OHLCChart02().getChart());
    Rectangle pageSize = new Rectangle(800, 600);
    createPdf(charts, "/root/xchart/chats", pageSize);
  }

  public static void createPdf(List<Chart> charts, String fileName, Rectangle pageSize) {
    Document document = new Document(pageSize);
    OutputStream os = null;
    try {
      os = new FileOutputStream(fileName);
      PdfWriter writer = PdfWriter.getInstance(document, os);
      document.open();
      PdfContentByte pb = writer.getDirectContent();
      Graphics2D g2 = null;
      Chart chart = null;
      for (int i = 0; i < charts.size(); i++) {
        g2 = new PdfGraphics2D(pb, pageSize.getWidth(), pageSize.getHeight());
        chart = charts.get(i);
        chart.paint(g2, chart.getWidth(), chart.getHeight());
        g2.dispose();
        if (i < charts.size() - 1) {
          document.newPage();
        }
      }
    } catch (FileNotFoundException e) {
      e.printStackTrace();
    } catch (DocumentException e) {
      e.printStackTrace();
    } finally {
      document.close();
      if (os != null) {
        try {
          os.close();
        } catch (IOException e) {
          e.printStackTrace();
        }
      }
    }
  }
```
The speed is several times faster than the above, the effect is as follows:
![Screenshot_2019-11-16_16-53-19](https://user-images.githubusercontent.com/57353473/68991176-d3d09400-0896-11ea-9fef-821cef91bafe.png)

**Comment by Mr14huashao** [comment]
@timmolter 
I have mentioned the issue on `vectorgraphics2d`, link: https://github.com/eseifert/vectorgraphics2d/issues/73,` vectorgraphics2d` does not support importing multiple Charts into one PDF file, and the export of PDF files is slow. , Will add new dependencies to export PDF files, I think itext is very good, above I have submitted the test code.
I hope you take the time to see it.

**Comment by timmolter** [comment]
iText looks good and I'd switch to it if it's faster, but the license is more restricted than the Apache License. Maybe there's a newer lib for SVG and PDF that's MIT or Apache License???

**Comment by Mr14huashao** [comment]
@timmolter 
itext: AGPL license requirements are very strict and unfriendly
pdfbox-graphics2d: Apache License Version 2.0, supports saving pdf files, not saving EPS, SVG

**Comment by Mr14huashao** [comment]
@timmolter 
Is it possible to add pdfbox-graphics2d dependency?

GitHub address: https://github.com/rototor/pdfbox-graphics2d

**Comment by timmolter** [comment]
yes, please replace the erichseifert PDF stuff with the pdfbox-graphics2d lib. Thanks!

**Comment by Mr14huashao** [comment]
Ok
