### ISSUE TITLE
Legend is invisible after defining custom font 

### ISSUE THREAD

**Issue by DRSchlaubi** [knowm/XChart#286]
I tried to create a pie chart with the ProductSans font
```Java
 Font font = Font.createFont(Font.PLAIN, new File("fonts/", "Product Sans Regular.ttf"));
        styler.setChartBackgroundColor(Colors.FULL_WHITE)
                .setLegendBackgroundColor(Colors.NOT_QUITE_BLACK)
                .setPlotBackgroundColor(Colors.BLURPLE)
                .setAnnotationsFont(font)
                .setLegendFont(font)
                .setToolTipFont(font)
                .setChartFontColor(Color.MAGENTA)
        ;
```

The Chart got generated like this
```Java
public PieChart(String heading, PieTile[] pieTiles) throws IOException, FontFormatException {
        this.heading = heading;
        this.chart = createChart();
        for (PieTile pieTile : pieTiles) {
            chart.addSeries(pieTile.getTile(), pieTile.getPercentage());
        }
        style(chart.getStyler());
    }
```
but unfortunately the legend font is completly invisible

**Comment by timmolter** [comment]
I never tried adding a font like that before, so I cannot say what they issue is. Does loading a font like that work in other instances like adding it to a JPanel?

**Comment by DRSchlaubi** [comment]
Fixed it because you need to set a font size otherwise the fint size is 1 and you cant see it

**Comment by ouryperd** [comment]
@DRSchlaubi could you perhaps give a short example ? I can't get a custom for to work.

`Font font = Font.createFont(Font.PLAIN, new File("fonts/", "Data.ttf"));
chart.getStyler().setAxisTickLabelsFont(font, Font.PLAIN, 10);`
