### ISSUE TITLE
Combine markers with error bars (markers = data) with line (= model prediction)

### ISSUE THREAD

**Issue by seppro** [knowm/XChart#289]
It is common in technical and natural sciences to have measured data with errors and model which approximates them, see eg:

https://upload.wikimedia.org/wikipedia/commons/f/f4/Time_profile_of_the_774_AD_spike_in_C-14..jpg

Both, error bars and line chart are "XYChart", but there is a global setting which switches between markers and lines (as far as I understand) :

chart.getStyler().setDefaultSeriesRenderStyle(XYSeries.XYSeriesRenderStyle.Scatter);

or 

chart.getStyler().setDefaultSeriesRenderStyle(XYSeries.XYSeriesRenderStyle.Line);

I cannot get it run correctly, if I do not print "line" data at all, then marker-data are OK. However if code contains "XYSeriesRenderStyle.Line" then two lines appear: markers are connected with line (this is unwanted) and  also "line-data" are displayed (which is fine).

Is it possible to display markes (not connected with line, with error bars), and a line (second data sample, not going throug markers)?

Thanks.

**Comment by timmolter** [comment]
Like this? See the following commit: <https://github.com/knowm/XChart/commit/bed6bb1f387506def3a0714c7e049a9f177c4a91>

![screen shot 2018-11-28 at 10 11 59](https://user-images.githubusercontent.com/738972/49141089-1b60b780-f2f6-11e8-8910-72826fc9fe45.png)

**Comment by seppro** [comment]
Exactly... How you did it?

**Comment by timmolter** [comment]
See the following commit: <https://github.com/knowm/XChart/commit/bed6bb1f387506def3a0714c7e049a9f177c4a91>

**Comment by seppro** [comment]
Thank you very much.
