### ISSUE TITLE
Remove Y-axis after adding multiple Y-axis

### ISSUE THREAD

**Issue by timpehr** [knowm/XChart#291]
How do you remove a Y-axis after adding multiple Y-axis.   I'm working on an application that adds and removes series from the chart and adds multiple Y-axis.  I need to be able to remove a Y-axis at any point.
Example:
XYSeries series1;
XYSeries series2;
series1.setYAxisGroup(0);
chart.getStyler().setYAxisGroupPosition(0, Styler.YAxisPosition.Left); 
series2.setYAxisGroup(1);
chart.getStyler().setYAxisGroupPosition(1, Styler.YAxisPosition.Right); 

This shows two series on two Y-axis.  But now I want to delete one of the series and only show one Y-axis on the chart.  How do I do this?  I can remove the second series but the chart still shows the second Y-axis.

**Comment by hakantkn** [comment]
Pull #295 should solve this I guess.

**Comment by timpehr** [comment]
Thanks.  Any idea on when the next release will happen?  We are at the latest 3.5.2 and we really can't do incremental pull requests to get XChart approved to be installed.

**Comment by hakantkn** [comment]
Pull requests are usually merged in 1-2 days. But I have no idea when the next release will be.

**Comment by timmolter** [comment]
i'll try to cut a release in a day or two.

**Comment by timmolter** [comment]
new release is out!
