### ISSUE TITLE
Add annotation of line style category chart

### ISSUE THREAD

**Issue by ccyanthony** [knowm/XChart#306]
I found annotation cannot show while trying to using line style on category chart.
I want to have bar and line series on same chart with both annotation, however no annotation shown with line, it can be shown on both series when I change back the line series to bar.

**Comment by Mr14huashao** [comment]
@ccyanthony 
Only CategorySeriesRenderStyle.Bar, annotation will take effect.

This issue is not a problem and can be closed.
