### ISSUE TITLE
How to do not pop java window?

### ISSUE THREAD

**Issue by joey-happy** [knowm/XChart#309]
It will pop one java window when build a new XYChart object with XYChartBuilder.build().
How to do not pop java window?

**Comment by tomassvensson** [comment]
Please post some code

**Comment by Mr14huashao** [comment]
@YaoZhichao
No java window pops up, there should be no call to display chart method. 
You should look at README.md, that will give you some help.

pop java window，following code：
```java
  XYChart chart = new XYChartBuilder().build();
  new SwingWrapper<XYChart>(chart).displayChart();
```
