### ISSUE TITLE
Bar Chart doesn't draw smallest series in front when overlapping

### ISSUE THREAD

**Issue by phoeft670** [knowm/XChart#312]
It looks like the Series in Bar Chart Plots are drawn in Input Order. This leads to color issues and disappearing bars. A draw order related to the bar height would be nice.

![test](https://user-images.githubusercontent.com/25980181/57130511-fa672b80-6d99-11e9-856b-f1886ee1d2a3.png)

**Comment by Mr14huashao** [comment]
@timmolter 
This is a bug, this is not an overlapping histogram, there is no addition, it is just drawn together.

**Comment by timmolter** [comment]
In this case use `chart.getStyler().setOverlapped(false);`, which is the default.
