### ISSUE TITLE
Add cursor support

### ISSUE THREAD

**Issue by thhart** [knowm/XChart#317]
A cursor is a nice feature for a chart for multiple reason:
1. It looks nice to have a visual navigation marker
2. A cursor could help to display specific values (like tooltip)
3. A cursor set to a specific series value programmatically helps to find values in the chart

**Comment by thhart** [comment]
I made a simple approach, please let me know if you are interested. I am committing this to my [fork](https://github.com/thhart/XChart) as a first test. This is a simple mouse move. However personally I am interested into the cursor setting from outside. This will be implemented soon.

![Peek 2019-05-17 14-19](https://user-images.githubusercontent.com/2632538/57927664-fe716e00-78ae-11e9-9660-5774151dbe30.gif)

**Comment by timmolter** [comment]
This is similar to `chart.getStyler().setToolTipsEnabled(true);`. If you could create a PR with a similar implememntation as `chart.getStyler().setToolTipsEnabled(true);`, then we're definitely interested.

**Comment by vvdavid** [comment]
Very nice feature, hope to see it implemented!

**Comment by Mr14huashao** [comment]
@timmolter 
This feature has been implemented, and the hint function has been adjusted.

PR #393 implemented.

**Comment by timmolter** [comment]
@Mr14huashao Thanks for all the improvements and management of issues and PRs. It's time for a new release. What do you think? Are there any other changes you want to make or tests you want to carry out before I push a jar to Maven Central??
