### ISSUE TITLE
Control axis margin width

### ISSUE THREAD

**Issue by phraktle** [knowm/XChart#325]
I would like to display two charts below each other where the data is properly aligned. However, the charts are misaligned due to different Y axis label widths. It would be great to have a way to specify the width.

<img width="228" alt="Screen Shot 2019-06-12 at 11 24 36" src="https://user-images.githubusercontent.com/333139/59339695-f1f10180-8d04-11e9-8d50-671ad33a4251.png">

**Comment by file59** [comment]
Have you found any workarounds? I'm currently making charts for a can bus analysis tool and the missalignment makes it kinda hard see the correlation between value changes. Thanks in advance
(picture for better idea of what I'm trying to say)
![charts](https://user-images.githubusercontent.com/52603977/60757748-cbc23700-a00e-11e9-99ce-bf2b936b6cd5.png)

**Comment by timmolter** [comment]
Please try out the latest snapshot jar. @hakantkn implemented this feature just now! Thanks, @hakantkn
