### ISSUE TITLE
AxisTickCalculator_Number infinite loop

### ISSUE THREAD

**Issue by math-th** [knowm/XChart#334]
Hello,

My code got stuck after 6 hours calculation so I can't exactly reproduce the issue, but I found the problem and the possible fix.

With VisualVM, I could find that my rendering Thread is stuck on **org.knowm.xchart.internal.chartpart.AxisTickCalculator_Number.calculate(AxisTickCalculator_Number.java:104)**

After checking the source, it seems that there is a possible infinite loop at this location.

`
while (significand >= 10 || significand == Double.NEGATIVE_INFINITY) {
    significand /= 10.0;
    exponent++;
}
`

I don't have the code background and the time to investigate more, but just by checking this code, if **significand** is  *Double.NEGATIVE_INFINITY* or *Double.POSITIVE_INFINITY* this loop will never end.

Should the loop condition be ?
`significand >= 10 && Double.isFinite(significand)`

After the loop, we could test **significand** value to assign a static value when it's too small.

Hope this helped.

Have a good day.

Mathieu

[Source file - AxisTickCalculator_Number.java](https://github.com/knowm/XChart/blob/f22ae8dc15480e4a92ca371074cd91ce7c1ec729/xchart/src/main/java/org/knowm/xchart/internal/chartpart/AxisTickCalculator_Number.java)

**Comment by math-th** [comment]
Hi,

After checking the whole value list in the serie, I found out that my serie contained one NaN value (but allong with other double values).

I don't know this library policy, if it should throw an Exception or if the user have to check his values before creating a serie ?

Mathieu

**Comment by timmolter** [comment]
Hey thanks! I'll add a fix for it.
