### ISSUE TITLE
Radar Graph styling is not applied

### ISSUE THREAD

**Issue by wwwuser08** [knowm/XChart#335]
Setting a style e.g, 
        RadarSeries series = chart.addSeries("data", data, labels);
        series.setLineWidth(5);
The line width is not applied as the BasicStroke is not used. It is missing in PlotContent_Radar doPaint.

**Comment by Mr14huashao** [comment]
Yes, it may be that the developer is missing. In the PlotContent_Radar.doPaint(Graphics2D g) method, forget to set g.setStroke(series.getLineStyle());
There may be very few people who care about this feature and have been discovered by you.
