### ISSUE TITLE
Zoom bug with multiple series

### ISSUE THREAD

**Issue by phraktle** [knowm/XChart#349]
The zooming feature introduced in #216 has a bug when multiple series are shown with disjunct data ranges. See attached video demonstrating the behavior:

![zoom-bug](https://user-images.githubusercontent.com/333139/67160333-efa45100-f34f-11e9-9dae-bfbc73533301.gif)

**Comment by hakantkn** [comment]
@phraktle can you post a sample code? I'll try to look when I have time.

**Comment by phraktle** [comment]
@hakantkn I don't have an isolated test case available, but you could just try with two series: one with X values between 0-100 and the other one with 70-80, for example.

**Comment by Mr14huashao** [comment]
@phraktle 
Can you provide data for these series?

**Comment by hakantkn** [comment]
Added a new class TestForIssue349.java in pull #368. But I could not reproduce the bug. Can you check this if this test has the same problem? You can omit button positioning at line 25.

**Comment by timmolter** [comment]
Yes, please check if it's now fixed using the Snapshot jar. Thanks!
