### ISSUE TITLE
Legend in ScroolPanel

### ISSUE THREAD

**Issue by andreauser** [knowm/XChart#350]
Hi

i'am using a Xchart, so, my question is regarding a lengend

is there a way to copy the legend in a scrool panel?

because in some cases the legend is drawn outside the graph area

thanks a lot

**Comment by Mr14huashao** [comment]
@andreauser 
Can't copy legend，the chart is drawn on the panel, like a picture

**Comment by andreauser** [comment]
Thanks for you feedback
i will recreate legend in Jtable by code
thanks
