### ISSUE TITLE
XYchart, reactivate Y axis autoscaling

### ISSUE THREAD

**Issue by landret** [knowm/XChart#353]
Hi,
when using XYChart, Y axis autoscaling is deactivated when calling XYChart.getStyler().setYAxisMin()
XYChart.getStyler().setYAxisMax()

Is it possible to reactivate autoscaling?
Thanks

**Comment by Mr14huashao** [comment]
Restore YAxisMin, YAxisMax default values

chart.getStyler().setXAxisMin(null);
chart.getStyler().setYAxisMin(null);

**Comment by landret** [comment]
@Mr14huashao  
thanks a lot !
