### ISSUE TITLE
Printable single sub plot panel in multipanel frame

### ISSUE THREAD

**Issue by massimilianoporzio** [knowm/XChart#355]
It would be nice if the user can choose to print a single chart inside a multipanel. Now the print menu is printing the entire JFrame

**Comment by Mr14huashao** [comment]
"Save As..." and "Export To..." are all operated on the current XChartPanel

Looked at the source code, "Print..." Print is the parent component of the current XChartPanel, which is the current JFrame

I want to print the current XChartPanel, it can be changed.

I don't know why the print function is so designed.

**Comment by massimilianoporzio** [comment]
I know.. I looked at the code. It is possible to set the window for the job
print to be the current graph panel?

Il mer 6 nov 2019, 03:48 Mr14huashao <notifications@github.com> ha scritto:

**Comment by Mr14huashao** [comment]
@massimilianoporzio 
Can print the current graphics panel, need to modify the source code, can not be achieved through the settings.

**Comment by Mr14huashao** [comment]
@timmolter 
Is "Print ..." the same as "Save As ...", "Export To ...", and print the currently selected Chart directly?

Or do you have any suggestions?
