### ISSUE TITLE
Reset Boom button is not displayed

### ISSUE THREAD

**Issue by Mr14huashao** [knowm/XChart#357]
@timmolter 
The first time you select the area, there is a match to the data, the Reset Boom button is displayed, and the map is redrawn; the area is selected again, the data is not matched, and the Reset button button disappears.
Looked at the source code, the selection area does not match the data, directly return false (causing the Reset button button will disappear), xData, yData, extraValues is the last data.

Source code, AxesChartSeriesNumericalNoErrorBars.filterXByValue() method:
```java
     If (remainingDataCount == length) {
       Return false;
     }
     If (remainingDataCount == 0) {
       Return false;
     }
```
Can it be changed to true here?
```java
     If (remainingDataCount == length) {
       Return false;
     }
     If (remainingDataCount == 0) {
       Return true;
     }
```

**Comment by timmolter** [comment]
I didn't write that zooming code. @hakantkn, could you perhaps take a look??

**Comment by hakantkn** [comment]
I'll try to look when I have time.

**Comment by Mr14huashao** [comment]
This bug is the same as issue #216,
The same phenomenon as landret said at the end

**Comment by landret** [comment]
I solved this issue this way : 
after zooming with an area selection with no data inside, we must set variable "filtered" to false in class "Selection Zoom"
