### ISSUE TITLE
PieChart can not specify the percentage value with two decimal like 98.76%？

### ISSUE THREAD

**Issue by Thinkzhuo** [knowm/XChart#362]

**Comment by Thinkzhuo** [comment]
package org.knowm.xchart.internal.chartpart;

import java.awt.*;
import java.awt.font.FontRenderContext;
import java.awt.font.TextLayout;
import java.awt.geom.*;
import java.awt.geom.Arc2D.Double;
import java.text.DecimalFormat;
import java.util.Map;
import org.knowm.xchart.PieSeries;
import org.knowm.xchart.PieSeries.PieSeriesRenderStyle;
import org.knowm.xchart.style.PieStyler;
import org.knowm.xchart.style.PieStyler.AnnotationType;

/** @author timmolter */
public class PlotContent_Pie<ST extends PieStyler, S extends PieSeries>
    extends PlotContent_<ST, S> {

  private final ST pieStyler;
  private final DecimalFormat df = new DecimalFormat("#.0");

**Comment by Thinkzhuo** [comment]
above is the "PlotContent_Pie" file ,in the last,you specified a constant decimalFormat,this is not friendly in fact

**Comment by timmolter** [comment]
Yeah, it looks like it's hard-coded. We can set the value formatting with `chart.getStyler().setDecimalPattern("#0.000");`, but not the percentage formatting. 

I'll leave this open as a feature request.
