### ISSUE TITLE
Styler theme info panel visibility overwrites legend visibility

### ISSUE THREAD

**Issue by dhendriks** [knowm/XChart#365]
In Styler.java, at line 102, I see:

    isLegendVisible = theme.isInfoPanelVisible();

This overwrites the legend visibility of the theme, which already sets isLegendVisible.

Line 102 should be:

    infoPanelVisible = theme.isInfoPanelVisible();

**Comment by Mr14huashao** [comment]
@dhendriks 
You are right, I will submit a PR
