### ISSUE TITLE
XYChart, individual y axis group decimal pattern

### ISSUE THREAD

**Issue by landret** [knowm/XChart#370]
Hi,
is it possible to set the decimal pattern of a Y axis groups?

I only found this function but it affects all Y axis groups : XYChart.getStyler().setYAxisDecimalPattern()

Thanks

**Comment by Mr14huashao** [comment]
@landret 
Chart does not use `yAxisDecimalPattern` property

**Comment by timmolter** [comment]
I didn't know it was not working. I'll add the BUG label.

**Comment by Mr14huashao** [comment]
@timmolter 
Last time I answered wrong.
XYChart.getStyler().setYAxisDecimalPattern() formatting is effective for all series yData.

demo
```java
    // Create Chart
    XYChart chart =
        new XYChartBuilder()
            .width(800)
            .height(600)
            .title(getClass().getSimpleName())
            .xAxisTitle("X")
            .yAxisTitle("Y")
            .build();

    // Customize Chart
    chart.getStyler().setLegendPosition(LegendPosition.InsideNE);
    chart.getStyler().setAxisTitlesVisible(false);
    chart.getStyler().setDefaultSeriesRenderStyle(XYSeriesRenderStyle.Line);
    chart.getStyler().setYAxisDecimalPattern("#.00");

    // Series
    chart.addSeries("a", new double[] {0, 3, 5, 7, 9}, new double[] {-3.211, 5.112, 9.258, 6.265, 5.222});
    chart.addSeries("b", new double[] {0, 1, 3, 8, 9}, new double[] {100, 200, 215, 300, 600}).setYAxisGroup(1);
    
    new SwingWrapper<XYChart>(chart).displayChart();
```
![Screenshot_2019-12-21_09-19-52](https://user-images.githubusercontent.com/57353473/71300818-68b53880-23d3-11ea-8159-2e66bfe03099.png)

Do different series need to be treated differently?

**Comment by timmolter** [comment]
XYChart.getStyler().setYAxisDecimalPattern() was intended to set the pattern for all series on the y-Axis.

I guess it would be possible to add a decimal pattern to each series that overrides the chart's pattern. I'll change this from `bug` to `feature request`.
