### ISSUE TITLE
Realtime chart about the X tick , why it can not to be smoothest, it will be getting bigger.

### ISSUE THREAD

**Issue by zhaohaipeng1** [knowm/XChart#371]
the file path: 
package org.knowm.xchart.demo.charts.realtime;
public class RealtimeChart06 implements ExampleChart<OHLCChart>, RealtimeExampleChart

we test the demo case from the source, the first tick is from 01-02 ~01-04 the tickunit is 2， but at last it will be 01-14 ~01-19 the tickunit is 5. 

is there any solution for it?

**Comment by timmolter** [comment]
I don't understand the problem. Can you further explain the issue please?

**Comment by zhaohaipeng1** [comment]
do you have the email ? now we have the requirement for XChart. and we have issue to resolve it

**Comment by rushing2019** [comment]
![real-time-char-question](https://user-images.githubusercontent.com/58501747/70119669-ce9c8300-16a5-11ea-924a-64597874dc71.png)
hi

**Comment by Mr14huashao** [comment]
new OHLCChartBuilder (). width (800)

The width is 800 by default, you can increase it.

**Comment by zhaohaipeng1** [comment]
> new OHLCChartBuilder (). width (800)
> 
> The width is 800 by default, you can increase it.
do you have time ,  we have one requirement about XChart, but there is an issue which we can not find solution. can you help me to check it

**Comment by Mr14huashao** [comment]
X tick is calculated automatically and is affected by styler.getXAxisTickMarkSpacingHint (), cahrt.width, xData.length.
X tick spacing cannot be specified.

**Comment by zhaohaipeng1** [comment]
> X tick is calculated automatically and is affected by styler.getXAxisTickMarkSpacingHint (), cahrt.width, xData.length.
> X tick spacing cannot be specified.

Maybe i did not descript my question clearly, for our requirement, X data is 15:01:01 and then increase one tick like 15:01:02, 15:01:03 and so one, we want to use the X tick like this. do you have some solution, thank you.

**Comment by rushing2019** [comment]
> > X tick is calculated automatically and is affected by styler.getXAxisTickMarkSpacingHint (), cahrt.width, xData.length.
> > X tick spacing cannot be specified.
> 
> Maybe i did not descript my question clearly, for our requirement, X data is 15:01:01 and then increase one tick like 15:01:02, 15:01:03 and so one, we want to use the X tick like this. do you have some solution, thank you.

The reported data points as shown in the figure, where the X value is a date type, our purpose is to keep the scale consistent with the X value of the data point
please check the attachment, thanks
![xchart-x-tickcout](https://user-images.githubusercontent.com/58501747/70416712-a5f7fd00-1a9a-11ea-8bfc-2e866cd881b8.png)

**Comment by Mr14huashao** [comment]
I see what you mean, XChart doesn't support it.

**Comment by zhaohaipeng1** [comment]
> I see what you mean, XChart doesn't support it.

do you have any good idea for this scenario?

**Comment by Mr14huashao** [comment]
have no good idea

**Comment by zhaohaipeng1** [comment]
> I see what you mean, XChart doesn't support it.
when the line chart is drawing and refresh still, how can i collect the old line chart , is it possiable i can see the previous drawed line? i mean the now time range  is 15:34:38 ~ 15:35:02 , i want to see and check the previous  range? how can i do for it.

**Comment by Mr14huashao** [comment]
Save the chart as an image or PDF file before refreshing the chart.
BitmapEncoder.saveBitmap (chart, "./Sample_Chart", BitmapFormat.PNG);
VectorGraphicsEncoder.saveVectorGraphic (chart, "./Sample_Chart", VectorGraphicsFormat.PDF);

**Comment by hakantkn** [comment]
You can manually set tick spaces. See https://github.com/knowm/XChart#customizing-axis-ticks--axis-labels

**Comment by Mr14huashao** [comment]
@hakantkn @timmolter 
Is it possible to customize gridStep so that the tick spacing can be controlled

**Comment by hakantkn** [comment]
When you manually set axis ticks, ticks are only painted on points given by override map. gripStep/tick spacing is controlled by you.

**Comment by hakantkn** [comment]
So when you add new data you can update the locations of ticks (where to paint ticks according to x axis). For example you can generate a tick for each 5 minutes.
But adding new data does not extend x axis length in pixel space. Adding new data makes each ticks closer in pixel space.

**Comment by Mr14huashao** [comment]
@hakantkn 
Instead of setting the pixel size between two ticks, specify the number of ticks between ticks (interval milliseconds)

```java
// double gridStep =
// timeSpans.get(++index).getUnitAmount()
// * timeSpans.get(index).getMagnitude(); // in time units (ms)
double gridStep = DAY_SCALE; // Custom tick interval milliseconds
```
In this way, the x-axis scale interval will not be affected by xData or other factors.

**Comment by hakantkn** [comment]
I added those lines to end of `RealtimeChart06.updateData` method:

```
    ohlcChart.updateOHLCSeries(SERIES_NAME, xData, openData, highData, lowData, closeData);
    Map<Double, Object> overrideMap = new TreeMap<Double, Object>();
    for (int i = 0; i < xData.size(); i += 5) {
      overrideMap.put((double) xData.get(i).getTime(), "point " + i);
    }
    ohlcChart.setXAxisLabelOverrideMap(overrideMap);
```

This is the result:
![axisOverride](https://user-images.githubusercontent.com/6737748/71173440-ccc0eb00-2273-11ea-9468-876474dde6d8.gif)

This code creates x ticks for each 5th data point, and labels it as "point" + index.

**Comment by Mr14huashao** [comment]
@hakantkn

**Comment by timmolter** [comment]
Thanks @hakantkn and @Mr14huashao
