### ISSUE TITLE
ResetButton position display abnormal

### ISSUE THREAD

**Issue by Mr14huashao** [knowm/XChart#374]
@hakantkn 
Set the ResetButton position to LegendPosition.OutsideE or LegendPosition.OutsideS. The ResetButton draws abnormally.

As follows: 
![002](https://user-images.githubusercontent.com/57353473/70120253-0c4ddb80-16a7-11ea-9b7b-70c326cbc18f.gif)

**Comment by hakantkn** [comment]
This placement calculation comes from ChartButton which only considers InsideX/InsideXY positions. When an outside position is given it places the button at 0,0. 
ChartButton is placed as a plot part which is drawn inside the plot content area so outside positions cannot be calculated easily.

**Comment by Mr14huashao** [comment]
Then create a new enumeration without using LegendPosition to avoid misunderstanding by users.

Add a property, whether to hide the resetButton. The resetButton sometimes obscures part of the data,  and it has a double-click mouse reset function.

**Comment by hakantkn** [comment]
> Add a property, whether to hide the resetButton. The resetButton sometimes obscures part of the data, and it has a double-click mouse reset function.

 `SelectionZoom.setResetByButton`

**Comment by Mr14huashao** [comment]
sorry, did not notice that the function has been implemented

**Comment by timmolter** [comment]
Can this issue be closed?

**Comment by Mr14huashao** [comment]
I closed
