### ISSUE TITLE
SelectionZoom triggers redraw chart multiple times

### ISSUE THREAD

**Issue by Mr14huashao** [knowm/XChart#375]
@hakantkn 

mousePressed(MouseEvent e): No need to repaint

mouseDragged(MouseEvent e): Calling repaint multiple times

mouseReleased(MouseEvent e): Once repaint

mousePressed,mouseDragged to draw the selection area, but also redrawn the chart.
When the amount of data is relatively large, drawing the chart will load slowly.

**Comment by hakantkn** [comment]
Those are for drawing selection area to give visual feedback. 
If performance is an issue just create a copy of SelectionZoom with repaint method commented on mousePressed and mouseDragged and clearing inside of paint method.

**Comment by Mr14huashao** [comment]
Draw SelectionZoom and repaint Chart separated just fine.

**Comment by timmolter** [comment]
Can I close this issue now? I'm a bit confused about whether or not this is a problem.

**Comment by Mr14huashao** [comment]
No problem, just when drawing the selection area, the Chart is also drawn at the same time.
