### ISSUE TITLE
Filled area affected, ghosting appears

### ISSUE THREAD

**Issue by Mr14huashao** [knowm/XChart#385]
Right-click,"Save As ...","Export To ...","Print ..." operations have an effect the filled area and ghosting appears.
as follows:
![005](https://user-images.githubusercontent.com/57353473/71355846-3ebe6a80-25bb-11ea-8a59-c0f315d798cf.gif)

It is normal for chart to be saved in the file.

**Comment by timmolter** [comment]
wow, that's weird. No idea...

**Comment by Mr14huashao** [comment]
I will analyze it when I have time

**Comment by Mr14huashao** [comment]
@timmolter 
This problem does not occur on win 10 systems.

In win7 and Ubuntu 16.04 systems, this problem does not occur through shortcut ctrlS, ctrlE, ctrlP operation.

It is verified that this code should cause ghosting
```java
private void doPop(MouseEvent e) {

  XChartPanelPopupMenu menu = new XChartPanelPopupMenu();
  menu.show(e.getComponent(), e.getX(), e.getY());
}
```
It should be affected after drawing JPopupMenu.
