### ISSUE TITLE
Zoom function improvement: Don't redraw when no points are selected.

### ISSUE THREAD

**Issue by timmolter** [knowm/XChart#389]
When selection an area on the chart between data points the chart should not be redrawn.

**Comment by timmolter** [comment]
Also, some times the `Reset Zoom` button does not react to a click.

**Comment by drrezeau** [comment]
I also noticed that when you select an area between two data points (no data within the selected area), after it redraws, the "reset zoom" button disappears and the only way for us to zoom back out is to zoom in on some data again.

**Comment by Mr14huashao** [comment]
@timmolter 
Tested, the Reset Zoom button a click is no problem, it is reactive, is the mouse not placed in the Reset Zoom button area?
