### ISSUE TITLE
Does LineChart has the propertiy to make the line be smooth?

### ISSUE THREAD

**Issue by Thinkzhuo** [knowm/XChart#394]

**Comment by Mr14huashao** [comment]
```java
xySeries.setSmooth(true);
```
But the feature has not been released yet.

**Comment by timmolter** [comment]
I'll try to push a release this weekend...

**Comment by pwankhed** [comment]
+1 @Thinkzhuo - This feature should really be helpful. At present the line looks like this, `setSmooth` will certainly make it look nice

![image](https://user-images.githubusercontent.com/16070238/72808384-59830e00-3c51-11ea-847b-ad77f74021f1.png)

**Comment by timmolter** [comment]
I pushed a release. Give it a try.

**Comment by Mr14huashao** [comment]
@timmolter 
This feature has been released, this issue can be closed.
