### ISSUE TITLE
BitmapEncoder.saveBitmap doesn't save legend

### ISSUE THREAD

**Issue by junste** [knowm/XChart#397]
Hi,

I use your fantastic library for creating charts. However, when saving a chart with BitmapEncoder, the chart is there but I don't get the legend on the right side as I do using the SwingWrapper.

I've mostly used your example code. Is there anything else I need to do to get the legend when saving the chart as an image?

/**
 * Creates a simple Chart and saves it as a PNG and JPEG image file.
 */
public class Example1 {
 
  public static void main(String[] args) throws Exception {
 
    PieChart chart = new PieChartBuilder().width(800).height(600).title("Pie Chart").build();
 
    // Customize Chart
    Color[] sliceColors = new Color[] { new Color(224, 68, 14), new Color(230, 105, 62), new Color(236, 143, 110), new Color(243, 180, 159), new Color(246, 199, 182) };
    chart.getStyler().setSeriesColors(sliceColors);
 
    // Series
    chart.addSeries("Gold", 24);
    chart.addSeries("Silver", 21);
    chart.addSeries("Platinum", 39);
    chart.addSeries("Copper", 17);
    chart.addSeries("Zinc", 40);

    BitmapEncoder.saveBitmap(chart, "./Sample_Chart", BitmapFormat.PNG);
    BitmapEncoder.saveBitmap(chart, "./Sample_Chart", BitmapFormat.JPG);
    BitmapEncoder.saveJPGWithQuality(chart, "./Sample_Chart_With_Quality.jpg", 0.95f);
    BitmapEncoder.saveBitmap(chart, "./Sample_Chart", BitmapFormat.BMP);
    BitmapEncoder.saveBitmap(chart, "./Sample_Chart", BitmapFormat.GIF);
 
    BitmapEncoder.saveBitmapWithDPI(chart, "./Sample_Chart_300_DPI", BitmapFormat.PNG, 300);
    BitmapEncoder.saveBitmapWithDPI(chart, "./Sample_Chart_300_DPI", BitmapFormat.JPG, 300);
    BitmapEncoder.saveBitmapWithDPI(chart, "./Sample_Chart_300_DPI", BitmapFormat.GIF, 300);
  }
}

Regards,
Stefan

**Comment by Mr14huashao** [comment]
@junste 
```java
set Style
// Customize Chart
chart.getStyler().setLegendVisible(true);
```
The next version, `chart.getStyler().IsLegendVisible()` is true by default.

**Comment by timmolter** [comment]
@Mr14huashao  It should always have been true by default. Not sure what got changed...

**Comment by Mr14huashao** [comment]
@timmolter 
See issue #365  and PR #369 
Someone incorrectly modified the value of `isLegendVisible`.

**Comment by timmolter** [comment]
thanks. New release and jar just pushed...
