### ISSUE TITLE
`PDFBox` - Missing dependency, failed import - 'org.apache.pdfbox'

### ISSUE THREAD

**Issue by gibhub-src** [knowm/XChart#403]
Hello guys,
I just opened the project (in Netbeans) and it needed "Resolve Project Problems" step. One file `PdfboxGraphicsEncoder.java` was showing import errors with:

```
import org.apache.pdfbox.pdmodel.PDDocument;
import org.apache.pdfbox.pdmodel.PDPage;
import org.apache.pdfbox.pdmodel.PDPageContentStream;
import org.apache.pdfbox.pdmodel.common.PDRectangle;
import org.apache.pdfbox.pdmodel.graphics.form.PDFormXObject;
```
Adding the maven dependency in `pom.xml` and redoing "Resolve Project Problems" step fixed it for me:
```
<dependency>
        <groupId>org.apache.pdfbox</groupId>
        <artifactId>pdfbox</artifactId>
</dependency>
```
Do you guys need to add it in `pom.xml` file?

**Comment by timmolter** [comment]
It's `<optional>true</optional>` in the parent pom, so you do need to manually add it to your pom if you will be exporting PDFs. For people who don't need to export PDFs they don't need the unnecessary dependency.
