### ISSUE TITLE
Y-Axis - Set color properties for each of multiple Y-Axes [Feature Request]

### ISSUE THREAD

**Issue by gibhub-src** [knowm/XChart#404]
First I would like to greet and thank you for the existence of the project. I was surprised that Java was a bit behind regarding `Charting, graphing & plotting` libraries.

And now to the problem. I could not find a way to change the color of an individual Y-Axis. Although it is arguably advised NOT to use multiple Axes, it still has its uses and showing multiple Axes in the same color makes things harder.
For example the demos `DateChart01 - Millisecond Scale with Two Separate Y Axis Groups` and `DateChart03 - Minute Scale with Two Separate Y Axis Groups` are so confusing. Even if we add the `YAxisGroupTitle` via `chart.setYAxisGroupTitle()` we still do not know which one of the series is being referred.

My recommendation is to extend `Chart.java` with additional `getYAxisGroupColor(int yAxisGroup)` & `setYAxisGroupColor(int yAxisGroup, Color yAxisColor)` - properties. Then in the respective Axis-Object (be it `Axis, AxisPair, AxisTick, AxisTitle, AxisTickMarks, AsxisTickLabels` and s.o.) set the color and `repaint()`.

So i believe it would be a good feature improvement, that would benefit a lot of users. 
Thank you guys!

**Comment by Mr14huashao** [comment]
@timmolter
This feature has been implemented and can be closed.

**Comment by gibhub-src** [comment]
Hello guys @Mr14huashao @timmolter ,
Thank you for extending the API with the `XY-Axis-Title-Color` feature and closing the relevant issues and PR -  #405 #407.
However I think there was a misunderstanding regarding the #404 issue. They seem to refer the same feature but the idea of the #404 [Feature Request] was that we enable color properties of the Axis-Objects themselves with their `AxisTicks` & `AxisLabel`- objects and NOT just the `AxisGroupTitle`-Obect which was referred by #405 . Something like the picture below:
![image](https://user-images.githubusercontent.com/59957829/75967825-aef73f80-5ecc-11ea-9c05-be31fe62d501.png)

I suggest we reopen #404 and will consider the changes @Mr14huashao did in the #407 to get some idea how we extend these properties via the `Styler`.

**Comment by Mr14huashao** [comment]
@gibhub-src 
You want to set the `axisTickLabels` and `axisTickMarks` colors of the X axis, Y axis, and multiple Y axes respectively.

`chart.getStyler().setAxisTickLabelsColor(Color.CYAN)` is valid for all AxisTickLabels.

`chart.getStyler().setAxisTickMarksColor(Color.BLUE)` is valid for all AxisTickMarks.

![image](https://user-images.githubusercontent.com/57353473/76046990-64dd8f00-5f9c-11ea-8c7f-99ea9f0a031f.png)

To take effect on X, Y, and multiple Y axes, need to add styles. I can submit a PR next week.

**Comment by gibhub-src** [comment]
That's right, each Y-Axis `TickLabels`  & `TickMarks` independently and matching the `Series`-color. Could be split into 2 cases:
 - first case, we set a flag in `Styler` that enables `Y-Axes` color matching `Series` color.
 - second would be `setYAxisGroupTickLabelColor(COLOR)` and `setYAxisGroupTickMarksColor(COLOR)` methods explicitly.

The second case should give us the options to choose if we need to `setYAxisGroupColor(COLOR)` for a whole `Y-Axis-Group` or setters for `TickMarksColor` and/or `TickLabelsColor` independently. Just a matter of setter-methods.
