### ISSUE TITLE
Y-AxisGroup (YAxisGroup) - Set title color properties for each of multiple Y-Axes [Feature Request]

### ISSUE THREAD

**Issue by gibhub-src** [knowm/XChart#405]
First I would like to greet and thank you for the existence of the project. I was surprised that Java was a bit behind regarding Charting, graphing & plotting libraries.

Related to #404 it would be good to have this options available and change the color of a single `Y-AxisGroupTitle`.
I already did some adjustments and was able to reach the following effects:

**_1. LineChart03a - Extensive Chart Customization (Y-Axis Title color)_**
![image](https://user-images.githubusercontent.com/59957829/72602449-97152d80-3917-11ea-9ee6-5a84ad1948fc.png)

**_2. DateChart01a - Millisecond Scale with Two Separate Y Axis Groups (title & color)_**
![image](https://user-images.githubusercontent.com/59957829/72602872-47833180-3918-11ea-92fe-5f5af7290e6c.png)

3. DateChart03a - Minute Scale with Two Separate Y Axis Groups (titled & colored)
![image](https://user-images.githubusercontent.com/59957829/72603083-a9dc3200-3918-11ea-88b9-c04070f64429.png)

Regarding the _3rd Example_ the original Example: **_DateChart03 - Minute Scale with Two Separate Y Axis Groups_** has a problem which I think should be described in a separate `Issue` too. Its `Lable` is misleading since the series are created in a mixed order, which seems to be critical. At lines:
https://github.com/knowm/XChart/blob/b800f6677c4a7346848dbc872812f8a029b1bf4a/xchart-demo/src/main/java/org/knowm/xchart/demo/charts/date/DateChart03.java#L77
https://github.com/knowm/XChart/blob/b800f6677c4a7346848dbc872812f8a029b1bf4a/xchart-demo/src/main/java/org/knowm/xchart/demo/charts/date/DateChart03.java#L78
It still assigns the `first`-default color to the first created series, which happened to be the second `series 2` series (Or just the Label - not quite sure which occurs first and if it just assigns the first series color to the second label). That way the `series` and `label` colors defer. It took a while to figure it out, but that just proves the reasoning of the `Color-Issue`.

In a second post bellow I will extend the writing and give details to the API-changes and will try to prepare a pull request.

**Comment by Mr14huashao** [comment]
@timmolter 
This feature has been implemented and can be closed.
