### ISSUE TITLE
Examples - XChartDemo->charts->date->DateChart03 - `Series`-colors and `Legend`-colors are confusing and might be misleading

### ISSUE THREAD

**Issue by gibhub-src** [knowm/XChart#406]
Hello guys,
I was reviewing the Demos and while figuring out and playing around with the #405 feature I realized that the `DateChart03` has some misleading presentation. Here how it looks according to the original example with the `YAxisTitles` added:

![image](https://user-images.githubusercontent.com/59957829/72605842-d0509c00-391d-11ea-8450-9d799842d898.png)
The problem is, that in the Demo-code the **"series 1"** (assigned higher-range values AND created first) is explicitly created at position **"1"**:
https://github.com/knowm/XChart/blob/b800f6677c4a7346848dbc872812f8a029b1bf4a/xchart-demo/src/main/java/org/knowm/xchart/demo/charts/date/DateChart03.java#L77
before the **"series 2"** which should occupy position **"0"** (Zero Based).
https://github.com/knowm/XChart/blob/b800f6677c4a7346848dbc872812f8a029b1bf4a/xchart-demo/src/main/java/org/knowm/xchart/demo/charts/date/DateChart03.java#L78

Now if the code applies the **"first"**-Color to **"series 2"** it does NOT apply the same color to **"series 2"** in the `Legend`...or...the opposite. It might just assign the "first"-Color (i quess the `Blue`) to the "series 1" in the Legend, which is created first, but occupies position index "2".

Anyway, I think you get the idea from the illustration.
This just shows us, that the `separate YAxis-Color` #404  & #405  concept is quite reasonable.
Best Regards guys!

**Comment by gibhub-src** [comment]
Hm..as I debug the Y-data values (yData1, yData2) it seems like it relates them properly regardless which one is created first. It is just a color-mixing problem which we (currently) have to refer explicitly and might need to implement some mechanism to refer those colors-indexing implicitly.

**Comment by Mr14huashao** [comment]
@gibhub-src 
This situation is also considered normal. When adding a series, the `lineColor` of the series is not set. The `lineColor` of the series is set in turn from `chart.getStyler().getSeriesColors()`.

Setting the series `lineColor` is the same as the group setting `YAxisGroupTitleColor`, so there is no confusion.

like this:
```java
XYSeries series1 = chart.addSeries("series1", xData1, yData1);
series1.setYAxisGroup(1);
series1.setLineColor(chart.getStyler().getSeriesColors()[0]);
XYSeries series2 = chart.addSeries("series2", xData2, yData2);
series2.setLineColor(chart.getStyler().getSeriesColors()[1]);

chart.setYAxisGroupTitleColor(1, chart.getStyler().getSeriesColors()[0]);
chart.setYAxisGroupTitleColor(0, chart.getStyler().getSeriesColors()[1]);
```
