### ISSUE TITLE
Wrong date values are displayed on X-axis 

### ISSUE THREAD

**Issue by pwankhed** [knowm/XChart#412]
I have created a line graph that shows the JVM's heap memory usage over a period of time, the update frequency is 2 seconds. I have configured the x-axis line chart as below,

`xyChart.getStyler().setDatePattern("DD/MMM - HH:mm:ss");`

My `date `datapoints are coming from this object,

`nodeRunTime = currMemObj.currNodeRunTime;`

and I am adding that to chart as below,

`usedHeapSeries = xyChart.addSeries(Ser1_UsedHeap, nodeRunTime, usedHeapMemData);`

With this configuration, when I run the chart, I can see a date coming as below:
(note the date is displayed as **_34 Feb_** when the actual date is 3 February. In the console, correct date is printed)

![image](https://user-images.githubusercontent.com/16070238/73698463-1d33c100-46d9-11ea-904b-8a49a6a77ad6.png)

When I checked the actual date that I am passing, I found it is being collected correctly but not being displayed in the proper format. Is this a defect? Am I missing something? Reproducible test case is attached here.

[398_code.zip](https://github.com/knowm/XChart/files/4150623/398_code.zip)

Thanks!

**Comment by timmolter** [comment]
`dd/MMM - HH:mm:ss`
<http://www.sdfonlinetester.info/#>

**Comment by pwankhed** [comment]
Thanks @timmolter for your help, that fixes the issue. Not sure how it was working earlier with though `DD/MMM` 

![image](https://user-images.githubusercontent.com/16070238/73754286-1601c700-475c-11ea-8d18-460dde97aab5.png)
