### ISSUE TITLE
Is there a way to connect points on a scatter plot?

### ISSUE THREAD

**Issue by CommanderTrip** [knowm/XChart#413]
![Capture](https://user-images.githubusercontent.com/53628883/73958668-df4bbe00-48cd-11ea-8d20-10b7f45a3139.PNG)

I am looking to create a plot like this. It was created in R through a CSV file. Is it possible to create a scatter plot and connect to the points with a line?

Thanks,
Jason

**Comment by timmolter** [comment]
A line chart is a scatter chart with the lines connected. I think though for that chart you'd need to create separate line series for all those "hairs".

**Comment by CommanderTrip** [comment]
I've tried to plot this; however, a line chart would automatically sort my points from least to greatest so I couldn't make a line chart that turns back on itself.

**Comment by timmolter** [comment]
I'm pretty sure a line chart doesn't sort points, and if it does, it's a bug. Can you post some sample code?

**Comment by CommanderTrip** [comment]
![Capture](https://user-images.githubusercontent.com/53628883/74030070-bf6ed580-4973-11ea-8085-9153ff427c0b.PNG)
Forgive me. It seems that when I tried to implement a line that turned back on itself before, I had made a mistake in plotting points. Thank you for your time and assistance.
