### ISSUE TITLE
How saving real time charts?

### ISSUE THREAD

**Issue by hannah2810** [knowm/XChart#416]
How can I save real-time charts as GIF?
I added this at the end of my code but it only saves the chart with the last update of the XYSeries:
`BitmapEncoder.saveBitmap(this.chart, "./Sample_Chart", BitmapFormat.GIF);`

**Comment by timmolter** [comment]
To make the gifs in the README, I did a screen recording and used some free software to convert it to a GIF. There is no supprt in XChart directly for that.
