### ISSUE TITLE
Controlling line width and height

### ISSUE THREAD

**Issue by bdot** [knowm/XChart#419]
Is there a property to control the width & height Plot Grid lines of axis chart so the excess ticks do not appear (highlighted in the screenshot - in red). Use case I have needs a proper box with flat finish on top & right. Tried playing with TickMarks by adjusting TickMarkLength, but they seem to affect all sides.

<img width="1385" alt="Screenshot 2020-02-24" src="https://user-images.githubusercontent.com/976841/75187835-d880d000-5742-11ea-8034-312e526ad928.png">

**Comment by Mr14huashao** [comment]
@bdot 
Set like this:
```java
chart.getStyler().setPlotContentSize(1);
```

**Comment by bdot** [comment]
This indeed helps. Thanks for the quick pointer @Mr14huashao 

Note: set the value to 0.96 to work with the layout I have and this gives flat finish to all sides.
