### ISSUE TITLE
Axis position

### ISSUE THREAD

**Issue by henriquesmith** [knowm/XChart#427]
Hi guys I'm using this Library to make my undergraduate thesis and I need move my axis position to (0;0) on center of my chart. anyone could tell me how I can do that? Somehow to make thoses axis be like a cross. P.s : Sorry about my English.

**Comment by Mr14huashao** [comment]
@henriquesmith 
X axis at the bottom, Y axis can only be on the left or right.

Can draw one X and Y axis:
![image](https://user-images.githubusercontent.com/57353473/76274972-0e829000-62bd-11ea-8151-bbbe5997e833.png)

code:
```java

    double[] xData_xAxis = new double[] {-4, -3, -2, -1, 0, 1, 2, 3, 4};
    double[] yData_xAxis = new double[] {0, 0, 0, 0, 0, 0, 0, 0, 0};

    double[] xData_yAxis = new double[] {0, 0, 0, 0, 0, 0, 0, 0, 0};
    double[] yData_yAxis = new double[] {-17, -3, -2, -1, 0, 1, 2, 3, 17};

    double[] xData = new double[] {-4, -3, -2, -1, 0, 1, 2, 3, 4};
    double[] yData = new double[] {17, 10, 5, 2, 1, 2, 5, 10, 17};

    // Create Chart
    XYChart chart =
        new XYChartBuilder()
            .width(800)
            .height(600)
            .title("ample Chart")
            .xAxisTitle("X")
            .yAxisTitle("Y")
            .build();
    chart.getStyler().setPlotContentSize(1);

    XYSeries xAxisSeries = chart.addSeries("xAxis", xData_xAxis, yData_xAxis);
    xAxisSeries.setMarker(SeriesMarkers.NONE);

    XYSeries yAxisSeries = chart.addSeries("yAxis", xData_yAxis, yData_yAxis);
    yAxisSeries.setMarker(SeriesMarkers.NONE);

    chart.addSeries("y=x² +1", xData, yData);

    // Show it
    new SwingWrapper<XYChart>(chart).displayChart();
```

**Comment by henriquesmith** [comment]
@Mr14huashao
Hi! How are U? Thanks so much for your answer;
.
Just one more question... in my chart the Max and Min values do not defined yet. Can I use the Width and Height of my panel?
Acadêmico de engenharia civil - Henrique Eduardo Smith

**Comment by Mr14huashao** [comment]
You can try to set the minimum and maximum values of the Y axis.
```java
    chart.getStyler().setYAxisMax(20d);
    chart.getStyler().setYAxisMin(-20d);
```
When creating a chart, you can specify the width and height.
```java
    // Create Chart
    XYChart chart =
        new XYChartBuilder()
            .width(800)
            .height(600)
            .title("ample Chart")
            .xAxisTitle("X")
            .yAxisTitle("Y")
            .build();
```

**Comment by Mr14huashao** [comment]
@henriquesmith 
Has your problem been solved?

**Comment by henriquesmith** [comment]
@Mr14huashao  Yes, It was. Thanks so much.  But now, another problem was show up. I need to do  my chart scrollable with mouse middle button and do a progressBar (this is annother topic)! P.s: I'm still learning about this Library

**Comment by Mr14huashao** [comment]
@henriquesmith 
There is no such function, you can continue to study, take a look at the `README`.

**Comment by henriquesmith** [comment]
whats up ? @Mr14huashao or anyOne else. Could U tell me how can I make my series do a offSet from the border?
![image](https://user-images.githubusercontent.com/59668175/77122272-f7aa0f00-6a1b-11ea-8e84-8691b2c9e75c.png)

**Comment by henriquesmith** [comment]
Hi. I fix that...I just tried change the plotContentSize value and that's worked it.Thanks for everything ^^
