### ISSUE TITLE
How to ensure the tick showed as the real tick and there is no repeated tick value between first and second tick when start to draw line .

### ISSUE THREAD

**Issue by zhaohaipeng1** [knowm/XChart#428]
when we use the realtime-type chart to start drawing line by using the data, and the first tick is 15:02:15 with  next value is 15:02:16, between the two value there are some grid vertical line, and under the vertical line there will be repeated value like 15:02:15. but when time is later , about for 10s it will be normal. can you help to improve the issue. thanks a lot.

**Comment by timmolter** [comment]
Can you paste sample code showing the issue please?

**Comment by zhaohaipeng1** [comment]
xychart.updateXYSeries("default" + taskInfo.getTaskName().split("-")[1],
                            isOnlineOrPowerMonitor ? taskInfo.getSeries().getxData() : taskInfo.getSeries().getxDate(),
                            taskInfo.getSeries().getyData(), null);

**Comment by zhaohaipeng1** [comment]
we use the updateXYSeries method to update data

**Comment by zhaohaipeng1** [comment]
getxData() and getyData() which from the NE reported

**Comment by Mr14huashao** [comment]
@zhaohaipeng1 
```java
// Series
chart.addSeries("seriesName", xData, yData);
```
Paste xData, yData data.

**Comment by zhaohaipeng1** [comment]
xdata which type is date[Thu Jan 01 15:29:38 GMT+08:00 1970, Thu Jan 01 15:29:39 GMT+08:00 1970, Thu Jan 01 15:29:40 GMT+08:00 1970, Thu Jan 01 15:29:41 GMT+08:00 1970]
ydata which type is data[3.0, 33.0, 19.0, 8.0]
xdata which type is date[Thu Jan 01 15:29:38 GMT+08:00 1970, Thu Jan 01 15:29:39 GMT+08:00 1970, Thu Jan 01 15:29:40 GMT+08:00 1970, Thu Jan 01 15:29:41 GMT+08:00 1970]
ydata which type is data[0.0, 35.0, 13.0, 6.0]
xdata which type is date[Thu Jan 01 15:29:38 GMT+08:00 1970, Thu Jan 01 15:29:39 GMT+08:00 1970, Thu Jan 01 15:29:40 GMT+08:00 1970, Thu Jan 01 15:29:41 GMT+08:00 1970]
ydata which type is data[0.0, 0.0, 0.0, 0.0]

above of the data which we have three line, and which line has four value, but line repeat the xdate value.

**Comment by rushing2019** [comment]
![picture](https://user-images.githubusercontent.com/58501747/76479465-d1e2a000-6446-11ea-82c2-0c7f08754530.png)

**Comment by Mr14huashao** [comment]
@zhaohaipeng1 
The solution is to set the value of xAxisTickMarkSpacingHint to a large value.
```java
chart.getStyler().setXAxisTickMarkSpacingHint(600);
```

**Comment by zhaohaipeng1** [comment]
we test it by using large value, but still exists, what is the relationship with the three parameters about setAxisTickMarkLength, setXAxisTickMarkSpacingHint, XYChartBuilder().title("").width. or i mean what those the specific functions. thanks about.

**Comment by zhaohaipeng1** [comment]
@Mr14huashao thanks a lot

**Comment by Mr14huashao** [comment]
@zhaohaipeng1 

`chart.getStyler().setXAxisTickMarkSpacingHint(600)` , this setting is in effect:
![image](https://user-images.githubusercontent.com/57353473/76606589-7b13be00-654d-11ea-9133-92817ed1ad42.png)

**Comment by Mr14huashao** [comment]
@zhaohaipeng1 
setAxisTickMarkLength: Is to set the length of the vertical line of the axis scale.
setXAxisTickMarkSpacingHint and chart.width: Controls the number of ticks on the axis.
![image](https://user-images.githubusercontent.com/57353473/76833013-7c066180-6865-11ea-8eaf-d1a060f0f85d.png)

Repeated ticks appear when xData.length is too small and chart.with is too long.
The best settings: chart.getStyler().setXAxisTickMarkSpacingHint(chart.getWidth() / (xData.size() - 1))
