### ISSUE TITLE
the method setYAxisDecimalPattern which version we can use

### ISSUE THREAD

**Issue by limitlesslive** [knowm/XChart#429]
the new packet version 3.6.1 has no method setYAxisDecimalPattern() ， which version we can use it

**Comment by Mr14huashao** [comment]
This is a property of the series.
You can try it like this:
```java
    // Series
    XYSeries series = chart.addSeries("seriesName", xData, yData);
    series.setYAxisDecimalPattern("##.00");
```

**Comment by limitlesslive** [comment]
> This is a property of the series.
> You can try it like this:
> 
> ```java
>     // Series
>     XYSeries series = chart.addSeries("seriesName", xData, yData);
>     series.setYAxisDecimalPattern("##.00");
> ```

I means that it has no this attribute in new Jar package version 3.6.1
![image](https://user-images.githubusercontent.com/8475905/76484456-cc8c5200-6454-11ea-8b6a-c046c9c697a4.png)
Which version will bring in

**Comment by limitlesslive** [comment]
![image](https://user-images.githubusercontent.com/8475905/76485051-4f61dc80-6456-11ea-9aea-9398d5cd430a.png)

**Comment by Mr14huashao** [comment]
@limitlesslive 
This feature has not been released yet.
Can you try this setting:
```java
chart.getStyler().setYAxisDecimalPattern("##.00");
```

**Comment by timmolter** [comment]
I'll push a release soon.

**Comment by timmolter** [comment]
3.6.2 has been released. Thanks @Mr14huashao for all the improvements!
