### ISSUE TITLE
The plot data beyond the XChartpanel

### ISSUE THREAD

**Issue by limitlesslive** [knowm/XChart#432]
I have a problem , I do not know How to solve it
Normal bar chart as shown below
![image](https://user-images.githubusercontent.com/8475905/76759912-9a1d8480-67c7-11ea-882e-d501754d1cfe.png)
but when I move the scroll bar on the right and then the Bar Chart shown below and Data is plotted beyond the panel
![image](https://user-images.githubusercontent.com/8475905/76760030-e7015b00-67c7-11ea-971a-f4b560af4b8d.png)

**Comment by limitlesslive** [comment]
@timmolter Looking forward to your reply

**Comment by Mr14huashao** [comment]
@limitlesslive 
Can you paste the code.

**Comment by Mr14huashao** [comment]
@limitlesslive 
Write a simple demo to reproduce this problem, I can help analyze it.

**Comment by limitlesslive** [comment]
> @limitlesslive
> Write a simple demo to reproduce this problem, I can help analyze it.

Thanks for your reply the demo below ,when you run this demo you can follow this step

- first:

![image](https://user-images.githubusercontent.com/8475905/76843049-2e462500-6876-11ea-8324-95772fb207a4.png)

-  second: click the maximize button

![image](https://user-images.githubusercontent.com/8475905/76843411-b62c2f00-6876-11ea-8c31-ac7625181a7a.png)

- Third:  the problem is below

![image](https://user-images.githubusercontent.com/8475905/76843346-9b59ba80-6876-11ea-97c4-d1c00bac435a.png)

- and the code is:

package org.knowm.xchart.demo.charts.date;

import org.knowm.xchart.XChartPanel;
import org.knowm.xchart.XYChart;
import org.knowm.xchart.XYChartBuilder;
import org.knowm.xchart.XYSeries;
import org.knowm.xchart.demo.charts.ExampleChart;
import org.knowm.xchart.style.Styler;
import org.knowm.xchart.style.markers.SeriesMarkers;

import java.awt.BorderLayout;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Random;

import javax.swing.JFrame;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;

/**
 * Millisecond Scale
 *
 * <p>Demonstrates the following:
 *
 * <ul>
 *   <li>Millisecond Scale
 *   <li>LegendPosition.OutsideS
 *   <li>Two YAxis Groups - both on left
 */
public class DateChart01 implements ExampleChart<XYChart> {

  public static void main(String[] args) {
    JFrame frame = new JFrame();
    ExampleChart<XYChart> exampleChart = new DateChart01();
    XYChart chart = exampleChart.getChart();
    XChartPanel oChartPanel = new XChartPanel<>(chart);
    JTabbedPane m_ResultPanel = new JTabbedPane();
    oChartPanel.setVisible(true);
    JScrollPane jScrollPane = new JScrollPane();
    jScrollPane.setViewportView(oChartPanel);
    jScrollPane.setVisible(true);
    m_ResultPanel.addTab("Test plot", jScrollPane);
    frame.add(m_ResultPanel, BorderLayout.CENTER);
    frame.pack();
    frame.setVisible(true);
  }

  @Override
  public XYChart getChart() {

    // Create Chart
    XYChart chart = new XYChartBuilder().width(1000).height(1500).title("Millisecond Scale").build();

    // Customize Chart
    chart.getStyler().setLegendPosition(Styler.LegendPosition.OutsideS);
    chart.getStyler().setLegendLayout(Styler.LegendLayout.Horizontal);
    chart.getStyler().setXAxisMaxLabelCount(20);
    chart.getStyler().setYAxisMax(10.0);

    // Series
    Random random = new Random();

    // generate data
    List<Date> xData1 = new ArrayList<Date>();
    List<Double> yData1 = new ArrayList<Double>();

    DateFormat sdf = new SimpleDateFormat("HH:mm:ss.S");
    Date date = null;
    for (int i = 1; i <= 20; i++) {

      try {
        date = sdf.parse("23:45:31." + (100 * i + random.nextInt(20)));
      } catch (ParseException e) {
        e.printStackTrace();
      }
      xData1.add(date);
      yData1.add(Math.random() * i);
    }
    XYSeries series = chart.addSeries("series 1", xData1, yData1);
    series.setMarker(SeriesMarkers.NONE);

    return chart;
  }
}

**Comment by limitlesslive** [comment]
where I can get 3.6.2 released version, and I can not find the package as the url https://knowm.org/open-source/xchart/
![image](https://user-images.githubusercontent.com/8475905/76948665-5a2edc80-6942-11ea-9250-5a111977c933.png)

**Comment by timmolter** [comment]
Sorry. It's fixed now.

**Comment by limitlesslive** [comment]
> Sorry. It's fixed now.

thanks very much

**Comment by Mr14huashao** [comment]
@limitlesslive 
Already solved:
![432](https://user-images.githubusercontent.com/57353473/77045273-d507fe00-69fb-11ea-9069-54d509913d60.gif)

**Comment by limitlesslive** [comment]
> @limitlesslive
> Already solved:
> ![432](https://user-images.githubusercontent.com/57353473/77045273-d507fe00-69fb-11ea-9069-54d509913d60.gif)



> @limitlesslive
> Already solved:
> ![432](https://user-images.githubusercontent.com/57353473/77045273-d507fe00-69fb-11ea-9069-54d509913d60.gif)

Thank you very much, Thank you very much @Mr14huashao @timmolter  when will the package 3.6.3 be released which can solve this problem，I want to use this package as soon as possible
