### ISSUE TITLE
PieChart plot alignement

### ISSUE THREAD

**Issue by zorator** [knowm/XChart#437]
I am rendering multiple PieChart into a pdf document, and I am trying to have them aligned : 
Graph background is in gray, plot and legend background in white.

![image](https://user-images.githubusercontent.com/4431570/77078297-ae939400-69f6-11ea-8d99-244be024e8ae.png)

Is there a way to specify a Plot width, a margin left, or to change the default alignement ?

**Comment by Mr14huashao** [comment]
@zorator 
Set legend's position:
```java
chart.getStyler().setLegendPosition(LegendPosition.InsideNE);
```
Set the size of the drawing area to avoid overlapping with legend:
```java
chart.getStyler().setPlotContentSize(0.8);
```
![image](https://user-images.githubusercontent.com/57353473/77130564-67a7ac00-6a93-11ea-9ff1-697c82fa8ec5.png)

**Comment by zorator** [comment]
Hi, thanks for the tip, but the plot is now too small...

I ended-up printing the chart in two images (one without legend, and one without plot and title) and then joining them in the pdf file.
