### ISSUE TITLE
Add a JPanel inside a Chart like a LabelInfo?

### ISSUE THREAD

**Issue by henriquesmith** [knowm/XChart#438]
![image](https://user-images.githubusercontent.com/59668175/77129963-bd993700-6a34-11ea-9048-5c1401f0df8e.png)
Hello to every one! I'm using this Library to make my undergraduated thesis, but I need to create a PDF archieve to show this ( Image above this text is whats I got). but I need something like this image below. SomeOne can help me with that? 
![image](https://user-images.githubusercontent.com/59668175/77130176-aad33200-6a35-11ea-88e1-84f2ccac890c.png)
@Mr14huashao plis give me a help with that
P.S: Sorry about my English.

**Comment by Mr14huashao** [comment]
Want to draw a second picture?

**Comment by henriquesmith** [comment]
@Mr14huashao  
No, I just want to put a drawing / figure on my chart, in the same way as shown in the second image.

**Comment by henriquesmith** [comment]
@Mr14huashao 
where I did a circle with a pen. I wanna put something like that in my chart too. I dont know, seems like a  information label about whats kind of transversal section (Civil enginnering´s stuff) that datas in  chart belong.

**Comment by Mr14huashao** [comment]
> @Mr14huashao
> Yes, actually Yep. I wanna draw a second image in my chart (If that is a image or a JPanel put into the chart with something like XYChart jPanel.add(ChartPart.add(JPanel)).

XChartPanel extends JPanel, can be used as a JComponent.

**Comment by Mr14huashao** [comment]
There are certain rules for drawing, not like a brush.
I don't know if it can be drawn into the shape you want.

**Comment by henriquesmith** [comment]
> There are certain rules for drawing, not like a brush.
> I don't know if it can be drawn into the shape you want.

How about the ChartPart ? cuz all those components (Chartparts) can be added to the chart area, isn't?

**Comment by henriquesmith** [comment]
I think that are some "misconceptions" . I just wanna put into my chart area a jPanel with for example with rectangle drawn inside of that jPanel. Like the image that i showed.

> > There are certain rules for drawing, not like a brush.
> > I don't know if it can be drawn into the shape you want.
> 
> How about the ChartPart ? cuz all those components (Chartparts) can be added to the chart area, isn't?

**Comment by Mr14huashao** [comment]
Yes, with Graphics2D g, you can draw what you want.

**Comment by timmolter** [comment]
If it's just a PDF you want for your thesis, just use something like Inkscape to make some vector drawings and combine stuff together. That would be way easier if it's just a one-time thing.

**Comment by henriquesmith** [comment]
Hi, bad news :( . I did a class that extends of the Jpanel class, and I tried make a cast to chartPart and than add to the chart using chart.addPlot Part(), but dons' t work.
`Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: views.panelSecao cannot be cast to org.knowm.xchart.internal.chartpart.ChartPart`

SomeOne could tell me why don't worked it?

**Comment by henriquesmith** [comment]
![image](https://user-images.githubusercontent.com/59668175/77241275-7c3c8f00-6bce-11ea-948a-4922592ce2ee.png)
Look. I did showed my panel in my plot Area.. but now i wanna to put then in another place of my plot area. some tips to that?
@Mr14huashao

**Comment by Mr14huashao** [comment]
> Hi, bad news :( . I did a class that extends of the Jpanel class, and I tried make a cast to chartPart and than add to the chart using chart.addPlot Part(), but dons' t work.
> `Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: views.panelSecao cannot be cast to org.knowm.xchart.internal.chartpart.ChartPart`
> 
> SomeOne could tell me why don't worked it?

Can you paste the code?

**Comment by Mr14huashao** [comment]
> ![image](https://user-images.githubusercontent.com/59668175/77241275-7c3c8f00-6bce-11ea-948a-4922592ce2ee.png)
> Look. I did showed my panel in my plot Area.. but now i wanna to put then in another place of my plot area. some tips to that?
> @Mr14huashao

Do you want to place the panel component anywhere in PlotContent_?

If this is the idea, sorry, I haven't tried it, and I haven't found any way to do it.

**Comment by hakantkn** [comment]
Maybe you can use custom plot parts system. With that you can add images, text, button in chart.  These parts use data coordinate to determine their places. See https://github.com/knowm/XChart/pull/305 for an image (source for that image is TestForCustomChartParts.java).)

If you have a static image you can use  ChartImage class. Otherwise check ChartImage source code to position your panel.

**Comment by henriquesmith** [comment]
Finally! Yes.

Em Seg, 23 de mar de 2020 02:32, Mr14huashao <notifications@github.com>
escreveu:

**Comment by henriquesmith** [comment]
> Maybe you can use custom plot parts system. With that you can add images, text, button in chart. These parts use data coordinate to determine their places. See #305 for an image (source for that image is TestForCustomChartParts.java).)
> 
> If you have a static image you can use ChartImage class. Otherwise check ChartImage source code to position your panel.

it worked! Tks so much,You saved me.

**Comment by henriquesmith** [comment]
Just one last thing.Can I change the decimal places after the dot?
Cuz 0.05 is almost Zero, or for us Enginners, that value is one! dsauhdashud

**Comment by hakantkn** [comment]
styler.setXAxisDecimalPattern(xAxisDecimalPattern)
styler.setYAxisDecimalPattern(xAxisDecimalPattern)
