### ISSUE TITLE
Some plots are not drawn with the colour I set

### ISSUE THREAD

**Issue by elkrari** [knowm/XChart#440]
I'm drawing many plots in the same chart, half of them are in blue, the others are red.
But the chart display (sometimes) some of them in different colours. 

for (int k=0;k<nbrRuns;k++) {
	// Series
	XYSeries series1 = chart.addSeries("Hash"+k, xData, results1[k]);
	series1.setLineColor(XChartSeriesColors.BLUE);
	XYSeries series2 = chart.addSeries("Fitness"+k, xData, results2[k]);
	series2.setLineColor(XChartSeriesColors.RED);
}
![image](https://user-images.githubusercontent.com/3809431/77666290-13b03200-6f81-11ea-83ab-0680235e7e87.png)

**Comment by Mr14huashao** [comment]
@elkrari 
This is caused by drawing markers.
There are two ways to solve it:
- Don't draw marker:
```java
series1.setMarker(SeriesMarkers.NONE);
series2.setMarker(SeriesMarkers.NONE);
```
- Set marker color, same as line color:
```java
series1.setMarkerColor(XChartSeriesColors.BLUE);
series2.setMarkerColor(XChartSeriesColors.RED);
```
