### ISSUE TITLE
I have created donut chart in PDF using Xchart along with iText. While opening it from Acrobat readder, i am getting some lines between donut area. Below is the code that i have used. Please suggest what may be the reason for these lines coming between dontu.  Also, when i am opening same PDF using some other tool, then it is coming fine.

### ISSUE THREAD

**Issue by AkashSaini4646** [knowm/XChart#444]
I have created donut chart in PDF using Xchart along with iText. While opening it from Acrobat readder, i am getting some lines between donut area. Below is the code that i have used. Please suggest what may be the reason for these lines coming between dontu.

Also, when i am opening same PDF using some other tool, then it is coming fine.

Code:

import java.awt.Color;
import java.awt.Font;
import java.io.FileOutputStream;
import java.io.IOException;

import org.knowm.xchart.BitmapEncoder;
import org.knowm.xchart.BitmapEncoder.BitmapFormat;
import org.knowm.xchart.PieChart;
import org.knowm.xchart.PieChartBuilder;
import org.knowm.xchart.PieSeries.PieSeriesRenderStyle;
import org.knowm.xchart.SwingWrapper;
import org.knowm.xchart.VectorGraphicsEncoder;
import org.knowm.xchart.VectorGraphicsEncoder.VectorGraphicsFormat;
import org.knowm.xchart.demo.charts.ExampleChart;
import org.knowm.xchart.style.PieStyler.AnnotationType;
import org.knowm.xchart.style.Styler.LegendPosition;

import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Image;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.pdf.PdfWriter;

public class DonutChart implements ExampleChart<PieChart> {

    public static void main(String[] args) {

        ExampleChart<PieChart> exampleChart = new DonutChart();
        PieChart chart = exampleChart.getChart();
        new SwingWrapper<PieChart>(chart).displayChart();
    }

    /* (non-Javadoc)
     * @see org.knowm.xchart.demo.charts.ExampleChart#getChart()
     */
    @Override
    public PieChart getChart() {

        // Create Chart
        PieChart chart = new PieChartBuilder().width(600).height(400).title("Donut Chart").build();

        // Customize Chart
        chart.getStyler().setLegendVisible(true);
        chart.getStyler().setChartTitleBoxBorderColor(Color.black);
        chart.getStyler().setChartTitleBoxBackgroundColor(new Color(0, 222, 0));
        chart.getStyler().setChartTitleFont(new Font(Font.SANS_SERIF, Font.PLAIN, 18));
        chart.getStyler().setLegendBackgroundColor(new Color(240, 240,230));
        chart.getStyler().setLegendBorderColor(Color.CYAN);
        //chart.getStyler().setChartTitleVisible(false);
        chart.getStyler().setAnnotationType(AnnotationType.Label);
        chart.getStyler().setHasAnnotations(false);
        //chart.getStyler().setAnnotationDistance(.7);
        chart.getStyler().setPlotContentSize(.9);
        chart.getStyler().setDonutThickness(.45);
        chart.getStyler().setChartBackgroundColor(Color.WHITE);
        chart.getStyler().setInfoPanelBorderColor(Color.WHITE);
        //chart.getStyler().setLegendBorderColor(Color.WHITE);
        chart.getStyler().setPlotBorderColor(Color.WHITE);
        chart.getStyler().setDefaultSeriesRenderStyle(PieSeriesRenderStyle.Donut);
        chart.getStyler().setBorderWidth(0);
        chart.getStyler().setLegendFont(new Font(Font.SANS_SERIF, Font.PLAIN, 20));
        chart.getStyler().setLegendPosition(LegendPosition.OutsideE);

        Color[] sliceColors = new Color[] { new Color(31, 43, 135), new Color(9, 179, 162), new Color(0, 0, 0),
                new Color(133, 129, 129), new Color(184, 180, 180),new Color(207, 207, 207) };

        chart.getStyler().setSeriesColors(sliceColors);

        // Series
        chart.addSeries("Office", 50);
        chart.addSeries("Multifamily", 10);
        chart.addSeries("Mixed use", 34);
        chart.addSeries("Hospitality", 22);
        chart.addSeries("Retail", 29);
        chart.addSeries("Industrial", 40);

        try {

            BitmapEncoder.saveBitmapWithDPI(chart, "D:\\Akash\\Workspace_OMS8.6main\\CHARTTEST\\Donut_Chart_300_DPI", BitmapFormat.PNG, 300);
            VectorGraphicsEncoder.saveVectorGraphic(chart, "./Donut_Chart", VectorGraphicsFormat.PDF);

            Document document = new Document(PageSize.A4);
            PdfWriter.getInstance(document, new FileOutputStream("D:\\Akash\\Workspace_OMS8.6main\\CHARTTEST\\Donut_Chart_300_DPI.pdf"));
            document.open();
            Image img = Image.getInstance("D:\\Akash\\Workspace_OMS8.6main\\CHARTTEST\\Donut_Chart_300_DPI.png");
            img.setAbsolutePosition(10,400);
            img.scaleAbsolute(300f, 250f);
            document.add(img);
            document.close();
            System.out.println("Done");

        } catch (IOException e) {
        } catch (DocumentException e1) {
        }

        return chart;
    }

}

**Comment by Mr14huashao** [comment]
@AkashSaini4646 
This problem occurs when using `iText` to save a PDF. There are two extra light-colored lines. Same problem as #346 , this has been explained.

You can use XChart 3.6.1 or later to save PDF files and make adjustments.

Save PDF file:
```java
VectorGraphicsEncoder.saveVectorGraphic(chart, "./Donut_Chart", VectorGraphicsFormat.PDF);
```
or
```java
PdfboxGraphicsEncoder.savePdfboxGraphics(chart, "./Donut_Chart");
```

**Comment by AkashSaini4646** [comment]
@Mr14huashao  
I require charts in a PDF along with other data and it is done by iText. Please let me know if it is some rendering issue which can be raised with iText?

**Comment by Mr14huashao** [comment]
Save chart as PDF file directly, there is such a problem sometimes.

If you save the chart as an image and then save the image to a PDF, no extra lines are found.

**Comment by AkashSaini4646** [comment]
Thanks for your help

**Comment by Mr14huashao** [comment]
Run your code and generate three files:
![Screenshot_2020-04-01_15-49-17](https://user-images.githubusercontent.com/57353473/78112630-13a4ac00-7431-11ea-9ab1-e0213e167c7d.png)
![Screenshot_2020-04-01_15-48-48](https://user-images.githubusercontent.com/57353473/78112657-1dc6aa80-7431-11ea-80aa-1a4bb4623271.png)
![Screenshot_2020-04-01_15-49-50](https://user-images.githubusercontent.com/57353473/78112688-27e8a900-7431-11ea-9ad0-0ba1acf22554.png)
