### ISSUE TITLE
Save List of XYCharts to PNG or PDF

### ISSUE THREAD

**Issue by adallolio** [knowm/XChart#448]
Hi.
It seems I cannot save to PNG (or also PDF would be good) a matrix of charts. I have used BitmapEncoder.saveBitmap(chart, "whatever", BitmapFormat.PNG) to save a single XYChart chart, but how do I save a List<XYChart> of charts?

Thanks 
Alberto

**Comment by Mr14huashao** [comment]
@adallolio 
Look at the method of this PdfboxGraphicsEncoder class.
`org.knowm.xchart.PdfboxGraphicsEncoder.savePdfboxGraphics(List<Chart>, String)`

**Comment by adallolio** [comment]
Hi. This will not work because that class implements List<Chart> whereas the list I have is for XYChart: List<XYChart>.
Indeed I get the error: no suitable method found for savePdfboxGraphics(List<XYChart>,String)

Alberto

**Comment by Mr14huashao** [comment]
@adallolio 
`XYChart` extends `Chart`, List <Chart> can be List <XYChart>, List <CategoryChart>, etc.

List <Chart> can add all extends Chart classes, you can add different types of Chart.

**Comment by Mr14huashao** [comment]
@adallolio 
You try like this:
```java
    List<Chart> charts = new ArrayList<>();
    charts.add(new XYChart(800, 600));
    charts.add(new XYChart(800, 600));
    charts.add(new XYChart(800, 600));
    try {
      PdfboxGraphicsEncoder.savePdfboxGraphics(charts, "filePath");
    } catch (IOException e) {
      e.printStackTrace();
    }
```

**Comment by Mr14huashao** [comment]
@adallolio 
This method parameter, I will optimize it later.
```java
savePdfboxGraphics(List< ? extends Chart> charts, String fileName)
```

**Comment by adallolio** [comment]
List<Chart> charts = new ArrayList<>();
    charts.add(new XYChart(800, 600));
    charts.add(new XYChart(800, 600));
    charts.add(new XYChart(800, 600));
    try {
      PdfboxGraphicsEncoder.savePdfboxGraphics(charts, "filePath");
    } catch (IOException e) {
      e.printStackTrace();
    }

this compiles yes. I will test it later.

Thanks

**Comment by adallolio** [comment]
Hi. I have cloned the last version and run mvn clean package  and mvn javadoc:aggregate. Then I moved the jar target/xchart-3.6.3-SNAPSHOT.jar into my application and recompiled my application (with ant). It compiles fine, but when it comes to use PdfboxGraphicsEncoder.savePdfboxGraphics I get this error: java.lang.ClassNotFoundException: de.rototor.pdfbox.graphics2d.PdfBoxGraphics2D

This is a bit strange since I have included "import org.knowm.xchart.PdfboxGraphicsEncoder;" in my java file and I see that rotor.pdfbox should be downloaded when I build xchart:
<dependency>
	<groupId>de.rototor.pdfbox</groupId>
	<artifactId>graphics2d</artifactId>
	<version>0.25</version>
</dependency>

So the jar xchart-3.6.3-SNAPSHOT.jar should have the package.
Am I using the wrong package in my application?
Could you help?

Thanks
Alberto

**Comment by adallolio** [comment]
Is it possible to save for example 2 (or more) XYcharts into a single PNG, instead of PDF?

Thanks
Alberto

**Comment by Mr14huashao** [comment]
> Hi. I have cloned the last version and run mvn clean package and mvn javadoc:aggregate. Then I moved the jar target/xchart-3.6.3-SNAPSHOT.jar into my application and recompiled my application (with ant). It compiles fine, but when it comes to use PdfboxGraphicsEncoder.savePdfboxGraphics I get this error: java.lang.ClassNotFoundException: de.rototor.pdfbox.graphics2d.PdfBoxGraphics2D
> 
> This is a bit strange since I have included "import org.knowm.xchart.PdfboxGraphicsEncoder;" in my java file and I see that rotor.pdfbox should be downloaded when I build xchart:
> <dependency>
> <groupId>de.rototor.pdfbox</groupId>
> <artifactId>graphics2d</artifactId>
> <version>0.25</version>
> </dependency>
> 
> So the jar xchart-3.6.3-SNAPSHOT.jar should have the package.
> Am I using the wrong package in my application?
> Could you help?
> 
> Thanks
> Alberto

xchart-3.6.3-SNAPSHOT.jar does not contain dependencies jars (eg graphics2d-0.25.jar), unlike springboot.jar, package dependencies jars.

You can manually add graphics2d-0.25.jar.

**Comment by Mr14huashao** [comment]
> Is it possible to save for example 2 (or more) XYcharts into a single PNG, instead of PDF?
> 
> Thanks
> Alberto

You can look at the Example2 class of the xchart-demo project.
https://github.com/knowm/XChart/blob/develop/xchart-demo/src/main/java/org/knowm/xchart/standalone/Example2.java
