### ISSUE TITLE
Donut when they are no Data

### ISSUE THREAD

**Issue by youssefaitlhaj** [knowm/XChart#451]
Hey, 
i want to know if there is a way to do my Piechart like in picture, when they are no data available.

Thank you.
![Donut](https://user-images.githubusercontent.com/22324463/79546547-e8f25e80-8092-11ea-89c7-75e9e6ea2b40.PNG)

**Comment by Mr14huashao** [comment]
@youssefaitlhaj 
Can not achieve the effect of the picture.

n the added series, all values ​​are equal to 0 or null, the pie chart is not drawn; at least one value is not equal to 0 or null.

**Comment by youssefaitlhaj** [comment]
@Mr14huashao Thank yuou for your answer, but i have another question please.
Is it possible to change the **Height** of the legend ? Or change the size of the **ColorBox** in the legend ?

**Comment by Mr14huashao** [comment]
@youssefaitlhaj 
sorry, can not.

`ColorBox` size is fixed 20.

**Comment by youssefaitlhaj** [comment]
@Mr14huashao Thank you.
