### ISSUE TITLE
Dynamic toolTip irrespective of actual location of line chart

### ISSUE THREAD

**Issue by pwankhed** [knowm/XChart#452]
Hello There. I have a query regarding the toolTipType behaviour.  

I have created a line charts that fetches CPU usage data from remote REST service and update in line chart as shown below. Based on polling interval, data is updated at 'n' seconds, the chart is being updated and repaint works perfectly fine.

Challenge is, when I need to see the trend, I need to follow the line to see the CPU usage at a given time, as shown below:

![image](https://user-images.githubusercontent.com/16070238/79623709-b3428980-8115-11ea-914c-3572ec6ef967.png)

Is there any way that I can freely use my pointer on chart and still see the toolTip? Something like shown below or available on this [page](https://www.highcharts.com/demo/line-boost)?

![image](https://user-images.githubusercontent.com/16070238/79623821-34018580-8116-11ea-945c-a5d083c30e6f.png)

Thanks!

**Comment by Mr14huashao** [comment]
@pwankhed 
You can set it like this: `xyChart.getStyler().setCursorEnabled(true)`

Do not use `ToolTips`, `xyChart.getStyler().setToolTipsEnabled(false)`

**Comment by pwankhed** [comment]
Thanks @Mr14huashao for your help, appreciate it. I gave it a try, it is working but I am seeing some issues with this. When I enabled this, I am seeing my line chart as shown below.

![image](https://user-images.githubusercontent.com/16070238/79799545-86c78100-8352-11ea-8111-ffb778205c40.png)

I tested this with both toolTip enabled and disabled but same results. It is important to note that this behaviour is random. I use timer to update the chart and repaint it in timer's interval.

**Comment by Mr14huashao** [comment]
@pwankhed 
The points are too dense and there are too many points in the same series.
I will modify that a series only displays one point information as the cursor moves.

**Comment by Mr14huashao** [comment]
@pwankhed 
I fixed this problem, you can use the source code to make a jar to see if it meets your needs.

**Comment by timmolter** [comment]
I'll push an official release soon.

**Comment by pwankhed** [comment]
Thanks @Mr14huashao for quick help, I will check it out and give that a try.

@timmolter thanks for your help too, appreciate if you could let me know once you push the fix, I can pick the final jar in my build then.

Thanks both and entire XChart team for amazing work :)
