### ISSUE TITLE
OHLC improvements

### ISSUE THREAD

**Issue by timmolter** [knowm/XChart#456]
I would suggest a few improvements with the OCHL charts:

1. The legend render type should be a line matching the (blue) line.
1. Multiple series get different "line" colors.
1. The default red and green should be "nicer", i.e. not 255,0,0 and 0,255,0. Can we pick better looking default colors?

<img width="800" alt="Screen Shot 2020-04-25 at 18 34 37" src="https://user-images.githubusercontent.com/738972/80285179-72ed9780-8723-11ea-888d-ad046d37e2f8.png">

**Comment by Mr14huashao** [comment]
@timmolter 
When OHLCChart.addSeries, ohlcSeriesRenderStyle is OHLCSeriesRenderStyle.Candle or OHLCSeriesRenderStyle.HiLo, can such series add multiple.
