### ISSUE TITLE
how to add data from mysql?

### ISSUE THREAD

**Issue by Hildantoretto** [knowm/XChart#461]
private void getChart() {
        String query = "SELECT MONTH(tgl) AS bulan, COUNT(*) AS jumlah_bulanan FROM tb_pembukuan GROUP BY MONTH(tgl)";
        Connection Koneksi;
        PreparedStatement statement;
        try {
            Koneksi = koneksi.getKoneksi();
            statement = Koneksi.prepareStatement(query);
            ResultSet rs = statement.executeQuery();
            while (rs.next()) {
                String nama = "data";
                String s1 = rs.getString("bulan");
                String s2 = rs.getString("jumlah_bulanan");
                int XData = new Integer(s1);
                int YData = new Integer(s2);

                CategoryChart chart = new CategoryChartBuilder().title("").xAxisTitle("").yAxisTitle("").build();
                chart.getStyler().setLegendPosition(LegendPosition.InsideNW);
                chart.getStyler().setHasAnnotations(true);
                chart.getStyler().setPlotBackgroundColor(new Color(255,255,255));
                chart.addSeries(nama, new int[]{XData}, new int[]{YData});
                XChartPanel lp = new XChartPanel(chart);
                jChartPanel1.removeAll();
                jChartPanel1.add(lp, BorderLayout.CENTER);
                jChartPanel1.validate();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
    }
![Screenshot (53)](https://user-images.githubusercontent.com/33963152/81775258-b2372900-9516-11ea-855b-dd69a51459e1.png)

**Comment by Mr14huashao** [comment]
You can try it like this:
```java
  private void getChart() {
    String query =
        "SELECT MONTH(tgl) AS bulan, COUNT(*) AS jumlah_bulanan FROM tb_pembukuan GROUP BY MONTH(tgl)";
    Connection Koneksi;
    PreparedStatement statement;
    List<String> xData = new ArrayList<>();
    List<Integer> yData = new ArrayList<>();
    try {
      Koneksi = koneksi.getKoneksi();
      statement = Koneksi.prepareStatement(query);
      ResultSet rs = statement.executeQuery();
      while (rs.next()) {

        // String s1 = rs.getString("bulan");
        // String s2 = rs.getString("jumlah_bulanan");
        // int XData = new Integer(s1);
        // int YData = new Integer(s2);

        xData.add(rs.getString("bulan"));
        yData.add(rs.getInt("jumlah_bulanan"));
      }
    } catch (SQLException e) {
      JOptionPane.showMessageDialog(null, e.getMessage());
    }
    String nama = "data";
    CategoryChart chart =
        new CategoryChartBuilder().title("").xAxisTitle("").yAxisTitle("").build();
    chart.getStyler().setLegendPosition(LegendPosition.InsideNW);
    chart.getStyler().setHasAnnotations(true);
    chart.getStyler().setPlotBackgroundColor(new Color(255, 255, 255));
    chart.addSeries(nama, xData, yData);
    XChartPanel<CategoryChart> lp = new XChartPanel<>(chart);
    jChartPanel1.removeAll();
    jChartPanel1.add(lp, BorderLayout.CENTER);
    jChartPanel1.validate();
  }
```

**Comment by Mr14huashao** [comment]
@Hildantoretto 
Whether it solves your problem?
