### ISSUE TITLE
Add JCheckBox in Donut Chart

### ISSUE THREAD

**Issue by youssefaitlhaj** [knowm/XChart#463]
Hey @Mr14huashao ,
Is there any way to add a JCheckBox to the chart.
Like this : 
![DonutChart](https://user-images.githubusercontent.com/22324463/83515350-8257c180-a4d5-11ea-825c-a747f97ab3fc.PNG)

Thanks in advance.

**Comment by Mr14huashao** [comment]
@youssefaitlhaj 
Can add `JCheckBox` to chart, call `chart.addPlotPart(chartPart)`, need to customize chartPart, put `JCheckBox` in custom chartPart, you can refer to `TestForCustomChartParts` class.

But there is no guarantee that the effect is the same as the above picture.

**Comment by timmolter** [comment]
This library wasn't designed to allow custom injection of components into the chart. You basically get the whole chart.
