### ISSUE TITLE
Obtain real size for screen data area

### ISSUE THREAD

**Issue by bbigcookie** [knowm/XChart#473]
We can get the width for XChartPanel by using getVisibleRect() method, but in some cases, the data area size is really useful. 
Hers's my test code:

-------------------------------------------------------------------------
```
public class TestXYChart extends XYChart {

    public TestXYChart(int width, int height) {
        super(width, height);
    }

    public TestXYChart(TestXYChartBuilder testXYChartBuilder) {
        super(testXYChartBuilder);
    }

    @Override
    public void paint(Graphics2D g2, int width, int height) {
        super.paint(g2, width, height);

        double iLocateX = width >>> 1;

        g2.setPaint(Color.red);

        Line2D line = new Line2D.Double(iLocateX, 0 + 30, iLocateX, height - 50);
        Line2D line2 = new Line2D.Double(15, 0 + 30, 15, height - 50);
        g2.draw(line);
        g2.draw(line2);
    }
    
}
```
-----------------------------------------------------------------------------------------------

```
public class TestXYChartBuilder extends XYChartBuilder{
    /**
     * return fully built XYChart
     *
     * @return a XYChart
     */

    @Override
    public XYChart build() {
        return new TestXYChart(this);
    }
}
```

-------------------------------------------------------------------------------------------------
```
public class LineChart01 implements ExampleChart<XYChart> {

  public static void main(String[] args) {

    ExampleChart<XYChart> exampleChart = new LineChart01();
    XYChart chart = exampleChart.getChart();
    new SwingWrapper<XYChart>(chart).displayChart();
  }

  @Override
  public XYChart getChart() {

    // generates Log data
    List<Integer> xData = new ArrayList<Integer>();
    List<Double> yData = new ArrayList<Double>();
    yData.add(0d);
    for (int i = -3; i <= 3; i++) {
      xData.add(i);
      yData.add(Math.pow(10, i));
    }

    XYChart chart = new TestXYChartBuilder().width(800)
        .height(600)
        .title("Powers of Ten")
        .xAxisTitle("Power")
        .yAxisTitle("Value")
        .build();

    // Customize Chart
    XYStyler styler = chart.getStyler();
    styler.setChartTitleVisible(true);
    styler.setLegendPosition(LegendPosition.InsideNW);
    // chart.getStyler().setYAxisLogarithmic(true);
    styler.setXAxisLabelRotation(45);
    styler.setXAxisMin(-3d);
    styler.setXAxisMax(3d);

    // Series
    chart.addSeries("10^x", yData);
    return chart;
  }
}
```
I want to draw a line **ONLY** in the data area, but I can not get the real size of this. The line will be out of area yet. So how can I get the real size of data area?

**Comment by Mr14huashao** [comment]
@bbigcookie 
Can't get `chart.getPlot().getBounds()` through `extends XYChart`.

You can try like this:
```java
import java.util.ArrayList;
import java.util.List;

import org.knowm.xchart.SwingWrapper;
import org.knowm.xchart.XYChart;
import org.knowm.xchart.XYChartBuilder;
import org.knowm.xchart.demo.charts.ExampleChart;
import org.knowm.xchart.style.XYStyler;
import org.knowm.xchart.style.Styler.LegendPosition;

public class TestForIssue473 implements ExampleChart<XYChart> {

  public static void main(String[] args) {

    ExampleChart<XYChart> exampleChart = new TestForIssue473();
    XYChart chart = exampleChart.getChart();
    new SwingWrapper<XYChart>(chart).displayChart();
  }

  @Override
  public XYChart getChart() {

    // generates Log data
    List<Integer> xData = new ArrayList<Integer>();
    List<Double> yData = new ArrayList<Double>();
    yData.add(0d);
    for (int i = -3; i <= 3; i++) {
      xData.add(i);
      yData.add(Math.pow(10, i));
    }

    XYChart chart =
        new XYChartBuilder()
            .width(800)
            .height(600)
            .title("Powers of Ten")
            .xAxisTitle("Power")
            .yAxisTitle("Value")
            .build();

    // Customize Chart
    XYStyler styler = chart.getStyler();
    styler.setChartTitleVisible(true);
    styler.setLegendPosition(LegendPosition.InsideNW);
    // chart.getStyler().setYAxisLogarithmic(true);
    styler.setXAxisLabelRotation(45);
    styler.setXAxisMin(-3d);
    styler.setXAxisMax(3d);

    // Series
    chart.addSeries("10^x", yData);

    // add ChartPart
    LinePart line = new LinePart();
    chart.addPlotPart(line);
    return chart;
  }

  @Override
  public String getExampleChartName() {
    return null;
  }
}
```
```java
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.geom.Line2D;
import java.awt.geom.Rectangle2D;

import org.knowm.xchart.internal.chartpart.ChartPart;

public class LinePart implements ChartPart {

  @Override
  public Rectangle2D getBounds() {
    return null;
  }

  @Override
  public void paint(Graphics2D g) {

    Rectangle2D bounds = g.getClip().getBounds2D();

    Line2D line =
        new Line2D.Double(
            bounds.getX(), bounds.getY(), bounds.getX(), bounds.getY() + bounds.getHeight());
    Line2D line2 =
        new Line2D.Double(
            bounds.getX() + bounds.getWidth() - 1,
            bounds.getY(),
            bounds.getX() + bounds.getWidth() - 1,
            bounds.getY() + bounds.getHeight());

    g.setPaint(Color.red);
    g.draw(line);
    g.draw(line2);
  }
}
```
Show:
![Screenshot_2020-06-16_15-39-31](https://user-images.githubusercontent.com/57353473/84745742-988e7300-afe7-11ea-97aa-54ab4416476f.png)

**Comment by bbigcookie** [comment]
> @bbigcookie
> Can't get `chart.getPlot().getBounds()` through `extends XYChart`.
> 
> You can try like this:
> 
> ```java
> import java.util.ArrayList;
> import java.util.List;
> 
> import org.knowm.xchart.SwingWrapper;
> import org.knowm.xchart.XYChart;
> import org.knowm.xchart.XYChartBuilder;
> import org.knowm.xchart.demo.charts.ExampleChart;
> import org.knowm.xchart.style.XYStyler;
> import org.knowm.xchart.style.Styler.LegendPosition;
> 
> public class TestForIssue473 implements ExampleChart<XYChart> {
> 
>   public static void main(String[] args) {
> 
>     ExampleChart<XYChart> exampleChart = new TestForIssue473();
>     XYChart chart = exampleChart.getChart();
>     new SwingWrapper<XYChart>(chart).displayChart();
>   }
> 
>   @Override
>   public XYChart getChart() {
> 
>     // generates Log data
>     List<Integer> xData = new ArrayList<Integer>();
>     List<Double> yData = new ArrayList<Double>();
>     yData.add(0d);
>     for (int i = -3; i <= 3; i++) {
>       xData.add(i);
>       yData.add(Math.pow(10, i));
>     }
> 
>     XYChart chart =
>         new XYChartBuilder()
>             .width(800)
>             .height(600)
>             .title("Powers of Ten")
>             .xAxisTitle("Power")
>             .yAxisTitle("Value")
>             .build();
> 
>     // Customize Chart
>     XYStyler styler = chart.getStyler();
>     styler.setChartTitleVisible(true);
>     styler.setLegendPosition(LegendPosition.InsideNW);
>     // chart.getStyler().setYAxisLogarithmic(true);
>     styler.setXAxisLabelRotation(45);
>     styler.setXAxisMin(-3d);
>     styler.setXAxisMax(3d);
> 
>     // Series
>     chart.addSeries("10^x", yData);
> 
>     // add ChartPart
>     LinePart line = new LinePart();
>     chart.addPlotPart(line);
>     return chart;
>   }
> 
>   @Override
>   public String getExampleChartName() {
>     return null;
>   }
> }
> ```
> 
> ```java
> import java.awt.Color;
> import java.awt.Graphics2D;
> import java.awt.geom.Line2D;
> import java.awt.geom.Rectangle2D;
> 
> import org.knowm.xchart.internal.chartpart.ChartPart;
> 
> public class LinePart implements ChartPart {
> 
>   @Override
>   public Rectangle2D getBounds() {
>     return null;
>   }
> 
>   @Override
>   public void paint(Graphics2D g) {
> 
>     Rectangle2D bounds = g.getClip().getBounds2D();
> 
>     Line2D line =
>         new Line2D.Double(
>             bounds.getX(), bounds.getY(), bounds.getX(), bounds.getY() + bounds.getHeight());
>     Line2D line2 =
>         new Line2D.Double(
>             bounds.getX() + bounds.getWidth() - 1,
>             bounds.getY(),
>             bounds.getX() + bounds.getWidth() - 1,
>             bounds.getY() + bounds.getHeight());
> 
>     g.setPaint(Color.red);
>     g.draw(line);
>     g.draw(line2);
>   }
> }
> ```
> 
> Show:
> ![Screenshot_2020-06-16_15-39-31](https://user-images.githubusercontent.com/57353473/84745742-988e7300-afe7-11ea-97aa-54ab4416476f.png)

**Comment by bbigcookie** [comment]
thanks a lot.
