### ISSUE TITLE
series being plotted in different color than what is in the legend, along with a rendering error

### ISSUE THREAD

**Issue by crowlogic** [knowm/XChart#480]
[screenshot of bug](https://i.imgur.com/ydOA3iW.png)

what could be happening to cause the plot lines to get plotted incorrectly and in the wrong color?

**Comment by crowlogic** [comment]
![Screenshot from 2020-06-23 22-41-07](https://user-images.githubusercontent.com/41244135/85492413-213a7f80-b5a3-11ea-916f-a7c9dd6b4789.png)

**Comment by crowlogic** [comment]
the chart is initialized with

`  private XChartPanel<XYChart> newAccountValueChartPanel()
  {
    chart = new XYChartBuilder().theme(ChartTheme.Matlab).build();
    synchronized (chart)
    {
      XYStyler styler = chart.getStyler();
      styler.setXAxisMin(MarketMaker.openTime);
      styler.setXAxisMax(MarketMaker.closeTime);
      styler.setDatePattern("kk:mm:ss.SSS");
      styler.setDefaultSeriesRenderStyle(XYSeriesRenderStyle.Step);
      styler.setMarkerSize(1);
      double[] transactionTimes = myAccount.getTransactionTimes(this);
      double[] accountValues = myAccount.getAccountValues(this);
      chart.addSeries("PnL", transactionTimes, accountValues, null).setYAxisGroup(0);

      chart.setYAxisGroupTitle(0, "PnL");
      chart.getStyler().setYAxisGroupPosition(0, Styler.YAxisPosition.Right);
      chart.setYAxisGroupTitle(1, "price");
      chart.getStyler().setYAxisGroupPosition(1, Styler.YAxisPosition.Left);
      chart.getStyler().setToolTipsEnabled(true);

      accountValueAndPriceChartPanel = new XChartPanel<>(chart);

      return accountValueAndPriceChartPanel;
    }
  }`

**Comment by crowlogic** [comment]
after the chart is initialized, the two series are added 
```
 SwingUtilities.invokeLater(() ->
        {

          double[] txnTimes;
          double[] txnPrices;
          synchronized (mainFrame.orderBook.taq)
          {
            txnTimes = mainFrame.getTradeTimes();
            txnPrices = mainFrame.getTradePrices();
          }

          if (txnTimes.length > 0 && txnPrices.length > 0)
          {
            synchronized (mainFrame.chart)
            {
              mainFrame.chart.addSeries("price-" + date, txnTimes, txnPrices, null).setYAxisGroup(1);
//              mainFrame.accountValueAndPriceChartPanel.revalidate();
//              mainFrame.accountValueAndPriceChartPanel.repaint();
            }
          }

          mainFrame.refresh();
        });
```

**Comment by Mr14huashao** [comment]
Can't see what went wrong with the code you provided.

Can provide a demo, I can see a similar effect when running.

**Comment by crowlogic** [comment]
@Mr14huashao Thank you for the quick reply. The entire source code is a personal project that I've invested a lot of time and energy into and cannot share the source publicly. I do not work for a corporation, its all my personal stuff, would you be willing to sign an NDA? I will pay you for the help if you name a price. thank you, stephencrowley214@gmail.com

**Comment by timmolter** [comment]
Is it really a different color? Looks the same to me. Can you use a pixel color tool and get the RGB values?

**Comment by crowlogic** [comment]
@timmolter all the series are red, (255,0,0)    they are the wrong color, because if you look at the legend, they are supposed to be different colors. the breakage happens after adding the 3rd series..

**Comment by timmolter** [comment]
Ah, yes of course. Somehow I missed that.

**Comment by timmolter** [comment]
We don't need your full proprietary program to test this. Just a single class with a main method that draws a chart showing the problem. If you can provide that, we can help you fix the issue. Sometimes pulling out the chart code from you program like this will reveal the issue was with your own program's code. If not, then it's a bug in XChart.

**Comment by crowlogic** [comment]
I will try that and get back to y'all. thanks for your help

**Comment by crowlogic** [comment]
@timmolter the bug somehow resolved itself after I refactored the code a bit :+1:
