### ISSUE TITLE
How do i set for YAxisTick normally when i set the XAxisTickMarkSpacingHint value bigger. 

### ISSUE THREAD

**Issue by wangputao1** [knowm/XChart#485]
i test use the LineChart02 demo, and i want to check see the normal YAxisTick , when i set XAxisTickMarkSpacingHint value bigger. 

![XTickValue450](https://user-images.githubusercontent.com/68259308/87371812-addfc880-c5b8-11ea-9086-94c6b4b23cb7.png)

**Comment by wangputao1** [comment]
when i set XAxisTickMarkSpacingHint value 440, it is normal for YAxisTick.

**Comment by wangputao1** [comment]
when i set XAxisTickMarkSpacingHint value 440, it is normal for YAxisTick. i could not put the second picture about the normal YAxisTick, and can you understand my question?

**Comment by wangputao1** [comment]
@Mr14huashao ？？

**Comment by Mr14huashao** [comment]
@wangputao1 
Please use the latest version.

**Comment by wangputao1** [comment]
@Mr14huashao  latest version, you mean it is not 3.6.1 ? and latest version there is no this issue, right?

**Comment by Mr14huashao** [comment]
3.6.2 There are problems with the previous version

**Comment by Mr14huashao** [comment]
@wangputao1 Did you switch the new version? There should be no problem.

**Comment by wangputao1** [comment]
yes, i switch the new one 3.6.4, it is ok. thanks a lot.

**Comment by Mr14huashao** [comment]
NO Thanks.
