### ISSUE TITLE
Is it possible to achieve transparent background in pie chart?

### ISSUE THREAD

**Issue by staho** [knowm/XChart#488]
Hello. I've been trying to generate a piechart as an asset to my pdf template.

I need it to be png with transparent background but I'm only getting black solid colour instead. 
![image](https://user-images.githubusercontent.com/17594777/87848893-9bc99700-c8e4-11ea-992d-8980cf562b1b.png)

Maybe I'm missing some property or doing something wrong with my colour settings. 

Thanks!

Here is my code :
``` java   
PieChart chart = new PieChartBuilder()
                .width(200)
                .height(200)
                .theme(Styler.ChartTheme.GGPlot2)
                .build();

        chart.getStyler().setLegendVisible(false);

        Color[] sliceColors = new Color[] {
                new Color(238, 88, 88), //red
                new Color(213, 122, 212), //purple
                new Color(106,230, 182), //mentol
                new Color(88,155,238) //baby blue
        };

        chart.getStyler().setSeriesColors(sliceColors);
        chart.getStyler().setChartTitleBoxVisible(false);
        chart.getStyler().setHasAnnotations(false);
        chart.getStyler().setChartBackgroundColor(
                new Color(255,255, 255, 0)
        );
        chart.getStyler().setPlotBackgroundColor(
                new Color(255,255, 255, 0)
        );
        chart.getStyler().setPlotBorderVisible(false);

        chart.addSeries("laptop", 65);
        chart.addSeries("pc", 10);
        chart.addSeries("tel", 12.5);
        chart.addSeries("winda", 12.5);

        BitmapEncoder.saveBitmap(chart, "./Sample_Chart", BitmapEncoder.BitmapFormat.PNG);
```

**Comment by Mr14huashao** [comment]
@staho

**Comment by staho** [comment]
Hi @Mr14huashao,

I've changed my code in a way that you suggested but there are no changes in the output image. 
The background is still black instead of transparent.

**Comment by Mr14huashao** [comment]
@staho 
try this:
```java
    chart.getStyler().setChartBackgroundColor(new Color(255, 255, 255));
    chart.getStyler().setPlotBackgroundColor(new Color(255, 255, 255));
```

**Comment by staho** [comment]
@Mr14huashao now the background is white instead of black but still not transparent. 
My expectation is that there is no implementation of an alpha channel to render the image.

I checked some code and found out that the background is created always as black and then two images are merged. 

I think that alpha channel is ignored when creating a plot background (canvas base for a plot).

**Comment by timmolter** [comment]
Please try: ` chart.getStyler().setChartBackgroundColor(new Color(255, 255, 255,0));`, setting the alpha channel to 0.

**Comment by staho** [comment]
@timmolter that was the first option which I described in the issue.

**Comment by Mr14huashao** [comment]
@staho 
You can try this method:
```java
  public static void saveBitmap(PieChart chart, String filePath, BitmapFormat bitmapFormat)
      throws IOException {
    OutputStream out = new FileOutputStream(new File(filePath));
    try {
      BufferedImage bufferedImage =
          new BufferedImage(chart.getWidth(), chart.getHeight(), BufferedImage.TYPE_INT_ARGB);
      Graphics2D graphics2D = bufferedImage.createGraphics();
      chart.paint(graphics2D, chart.getWidth(), chart.getHeight());

      ImageIO.write(bufferedImage, bitmapFormat.toString().toLowerCase(), out);
    } finally {
      out.close();
    }
  }
```
@timmolter 
The `BitmapEncoder.getBufferedImage(Chart chart)` method causes the problem, 
`BufferedImage.TYPE_INT_RGB` is changed to `BufferedImage.TYPE_INT_ARGB`, the chart is saved as an image, and the background color of the image is normal.

**Comment by staho** [comment]
@Mr14huashao it worked. Thanks! It'd be really awesome to apply this change to the XChart.

**Comment by timmolter** [comment]
Sorry for not reading your initial post more carefully. I'll change the code quick...

**Comment by timmolter** [comment]
OK, it should work now by using ` chart.getStyler().setChartBackgroundColor( new Color(255,255, 255, 0))`. You can try out the latest snapshot jar to test it.

**Comment by Mr14huashao** [comment]
@staho @timmolter The code is updated. After the test, the background of the exported image is not black. 
You do not need to set `alpha`. This is not a color transparency issue, but a background issue for generating images. 
```java
    chart.getStyler().setChartBackgroundColor(new Color(255, 255, 255));
    chart.getStyler().setPlotBackgroundColor(new Color(255, 255, 255));
```

**Comment by timmolter** [comment]
I thought that the default background had an alpha of 1, which would mean necessitating manually setting to background alpha to 0 to get the desired transparency. If it's now exporting with no transparency, then that would also be a bug in my opinion. In fact that might be why I set the type to `TYPE_INT_RGB` originally in:

```java
new BufferedImage(chart.getWidth(), chart.getHeight(), BufferedImage.TYPE_INT_ARGB);
```
