### ISSUE TITLE
How can i draw the combined domain xy which function like jfreechart's CombinedDomainXYPlot class.

### ISSUE THREAD

**Issue by wangputao1** [knowm/XChart#493]
![画图111111](https://user-images.githubusercontent.com/68259308/89380960-02471580-d72b-11ea-8106-e5a3d6250d9b.png)

**Comment by Mr14huashao** [comment]
@wangputao1 
This graph is not supported.

**Comment by chjan** [comment]
You can use swing or swingX and its splitpane feature, then launch to instances of Xchart in their respective slot. It is very easy;

`// Create splitpane on right to hold demo and source code
        splitPane = new AnimatingSplitPane(JSplitPane.VERTICAL_SPLIT);
        splitPane.setBorder(EMPTY_BORDER);
        mainPanel.add(splitPane, BorderLayout.CENTER);
        
        // Create panel to contain currently running demo
        topContainer = new JPanel();
        topContainer.setLayout(new BorderLayout());
        topContainer.setBorder(PANEL_BORDER);
        topContainer.setPreferredSize(new Dimension(DEMO_PANEL_WIDTH, DEMO_PANEL_HEIGHT));
        splitPane.setTopComponent(topContainer);

        currentDemoPanel = demoPlaceholder;
        topContainer.add(demoPlaceholder, BorderLayout.CENTER);
                
        // Create collapsible source code pane
        codeViewer = new CodeViewer();
        bottomContainer = new JPanel(new BorderLayout());
        bottomContainer.add(codeViewer);
        bottomContainer.setBorder(PANEL_BORDER);
        bottomContainer.setMinimumSize(new Dimension(0,0));
        splitPane.setBottomComponent(bottomContainer);`

**Comment by timmolter** [comment]
That exact chart type is not possible, but you could just create two charts like @chjan said and even hide the xaxis ticks and labels for the one chart. You's also have to manually set the min and max x-axis values for both charts.
