### ISSUE TITLE
Removing unavailable data XYChart

### ISSUE THREAD

**Issue by juliusquismundo** [knowm/XChart#496]
Hi. This may be simple, I just couldn't find a way to make the zeroes in this line chart to be removed. The goal here is to update the same chart every month by just plotting the next months values and not adding a month data in x so that the width of the chart is static. So I wanted to remove the Sep values and after. Is that possible?
![xychart](https://user-images.githubusercontent.com/33485960/89971926-1e006d80-dc8f-11ea-90a6-c973a5dc32f4.png)

**Comment by Mr14huashao** [comment]
![demo](https://user-images.githubusercontent.com/57353473/90135513-56926b00-dda5-11ea-815f-7980cf2d5b8a.png)

**Comment by juliusquismundo** [comment]
Wow. Thanks. It works. I was working with int primitives so null values didn't really came up to me. But thank you so much
