### ISSUE TITLE
what is the max value for Y axis, when i set the value for chart.getStyler().setYAxisMax(Double.MAX_VALUE); , the chart panel error occur .

### ISSUE THREAD

**Issue by wangputao1** [knowm/XChart#509]
public class LineChart01 implements ExampleChart<XYChart> , i test this demo, and i set the Y axis max value  to Double.MAX_VALUE. the exception occur. i want to know what is the actual max value about Y axis. thanks.

**Comment by wangputao1** [comment]
![max_y_value](https://user-images.githubusercontent.com/68259308/93202211-eb153200-f784-11ea-86b6-5c300eaeaefc.jpg)

**Comment by timmolter** [comment]
I got this (no exception):

<img width="800" alt="Screen Shot 2020-09-16 at 09 09 49" src="https://user-images.githubusercontent.com/738972/93303894-72ea5300-f7fc-11ea-93ae-f84af23ce1b4.png">

**Comment by wangputao1** [comment]
but we tried exception, can you give us the max value about Y axis.

**Comment by timmolter** [comment]
I think the max value is probably `Double.MAX_VALUE`.

**Comment by wangputao1** [comment]
![line2_max_y_value](https://user-images.githubusercontent.com/68259308/93307116-36861980-f833-11ea-8ec5-0d1bf90fb2a3.jpg)

**Comment by timmolter** [comment]
OK, LineChart02 gave me the exception and I pushed a fix. Please try with the latest SNAPSHOT build.
