### ISSUE TITLE
Labels in pie chart can't be shown with ticks

### ISSUE THREAD

**Issue by sabinkazairova** [knowm/XChart#514]
Hello, I am trying to make a pie chart with labels ticks. Seems doesnt work at all for me:
https://user-images.githubusercontent.com/50263002/95097833-38eedb80-072e-11eb-9df1-7c11d2cf6d38.png .

What i want is : 

https://user-images.githubusercontent.com/50263002/95097980-65a2f300-072e-11eb-9fe8-dd27f1b0c670.png

**Comment by timmolter** [comment]
`chart.getStyler().setAnnotationDistance(1.15);`

See `PieChart03.java` in the demo code.

**Comment by timmolter** [comment]
Any number above 1 moves the annotation outside the pie.
