### ISSUE TITLE
Customization options? - example

### ISSUE THREAD

**Issue by chjan** [knowm/XChart#515]
Would it be possible to customize Xchart, either by built in features, or by override, to something that resembles the following screenshot from REW (Room Eq Wisard), a very widely used tool when it comes to audio development of speakers, room threatment, etc.

Since REW is so widely used, it is a good thing to be as close as possible when it comes to other software applications that interacts with REW (as is our case).

In particular, the logarithmic plotting in the graph is wanted aeasthetics.

Thanks for a quick remark.

![RewGraphExample](https://user-images.githubusercontent.com/69140/95727012-eb1c2b00-0c79-11eb-88e0-60493fcb6647.PNG)

**Comment by timmolter** [comment]
Using `chart.getStyler().setXAxisLogarithmic(true);` you can achieve what you need. 

![Uploading Screen Shot 2020-10-24 at 19.30.42.png…]()

**Comment by timmolter** [comment]
Is this ok for you?
