### ISSUE TITLE
Regression on Y-axis for CategoryChart since 3.6.6

### ISSUE THREAD

**Issue by ybotquelen** [knowm/XChart#530]
Since I've migrated to version 3.6.6 from 3.6.5, I encounter the following regression on the category charts:
- The Y-axis display wrong values compared to the values of my bar series
see attached sample:
![YAxis regression](https://user-images.githubusercontent.com/75014204/100206314-74c04900-2f06-11eb-921c-983e39a8ad21.jpg)

Thank you in advance for your correction and thank you for your great library !

**Comment by timmolter** [comment]
Thank you for the bug report. Would it be possible to paste a short code snippet demonstrating the chart in code please?

**Comment by ybotquelen** [comment]
Hello, 
Please find below a sample class demonstrating the issue: 

`import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.concurrent.CopyOnWriteArrayList;

import org.apache.commons.lang3.tuple.Pair;

import org.knowm.xchart.CategoryChart;
import org.knowm.xchart.CategoryChartBuilder;
import org.knowm.xchart.CategorySeries;
import org.knowm.xchart.SwingWrapper;
import org.knowm.xchart.style.CategoryStyler;
import org.knowm.xchart.style.Styler.LegendPosition;


public class SampleRegression {

	public static final SimpleDateFormat sdfMonthYear = new SimpleDateFormat("MM/yyyy");

	public static void main(String[] args) {
		try {
			new SwingWrapper<CategoryChart>(getVolumesChart()).displayChart();
		}
		catch (Exception e) {
			e.printStackTrace();
		}

	}
	
	public static CategoryChart getVolumesChart() throws Exception {
		Pair<List<Date>, List<Double>> data;
		CategorySeries serie;
		List<Date> xSerie = null;

		// Création du graphe
		CategoryChart chart = new CategoryChartBuilder().width(800)
				.height(500).title("Volumes").xAxisTitle("Période").yAxisTitle("Volumes").build();

		// Définition du style du graphe
		CategoryStyler styler = chart.getStyler();
		styler.setLegendPosition(LegendPosition.InsideNW);
		styler.setLegendBackgroundColor(Color.DARK_GRAY);
		styler.setDatePattern("MM/yyyy");
		styler.setXAxisTickMarkSpacingHint(50);
		styler.setAntiAlias(true);
		styler.setChartTitleBoxBorderColor(Color.LIGHT_GRAY);
		styler.setToolTipsEnabled(true);
		styler.setOverlapped(false);
		styler.setStacked(true);
		styler.setChartBackgroundColor(Color.DARK_GRAY);
		styler.setChartFontColor(Color.LIGHT_GRAY);
		styler.setAxisTickLabelsColor(Color.LIGHT_GRAY);
		styler.setYAxisMax(Double.valueOf(100));

		for (int i = 0; i < 3; i++) {
			data = getSampleData(i);
			if (xSerie == null) {
				xSerie = data.getLeft();
			} 
			serie = chart.addSeries("Serie " + i, xSerie, data.getRight());
			serie.setChartCategorySeriesRenderStyle(CategorySeries.CategorySeriesRenderStyle.Bar);
		}
		return chart;
	}
	
	public static Pair<List<java.util.Date>, List<Double>> getSampleData(int i) throws Exception {
		List<java.util.Date> xData = new CopyOnWriteArrayList<java.util.Date>();
		List<Double> yData = new CopyOnWriteArrayList<Double>();
		
		xData.add(sdfMonthYear.parse("09/2020"));
		yData.add(Double.valueOf(20 + i));
		xData.add(sdfMonthYear.parse("10/2020"));
		yData.add(Double.valueOf(10 + i));
		xData.add(sdfMonthYear.parse("11/2020"));
		yData.add(Double.valueOf(30 + i));
		return Pair.of(xData, yData);
	}

}
`

**Comment by timmolter** [comment]
Thank you. Seems fixed now, on the latest SNAPSHOT version.

<img width="800" alt="Screen Shot 2020-11-27 at 9 50 53 AM" src="https://user-images.githubusercontent.com/738972/100429751-0f9b5d80-3096-11eb-8f17-7fc1ca46b4f9.png">
