### ISSUE TITLE
Add Automatic-Module-Name to Jar MANIFESTs for compatibility with modular applications

### ISSUE THREAD

**Issue by MrcJkb** [knowm/XChart#533]
At the moment, xchart cannot be used with Java 9+ modular applications.
This can be fixed by adding an Automatic-Module-Name to the Jar MANIFESTs.

See http://branchandbound.net/blog/java/2017/12/automatic-module-name/

**Comment by carlosame** [comment]
Normally, module names follow the reverse-DNS convention. For example see Stephen Colebourne's blog post:

https://blog.joda.org/2017/04/java-se-9-jpms-module-naming.html

> Module names must be **reverse-DNS**, just like package names, e.g. org.joda.time.

or Mark Reinhold's stance:

http://mail.openjdk.java.net/pipermail/jpms-spec-experts/2017-May/000687.html

> Strongly recommend that all modules be named according to the reverse Internet domain-name convention.

I wonder if `org.knowm.xchart` could be more appropriate than `knowm.xchart`.

**Comment by MrcJkb** [comment]
Agreed.

I would also propose incrementing the major version if this PR is merged, as this is a breaking change for modular projects that have so far depended on xchart.
Without the "Automatic-Module-Name" attribute, the module finder will derive an automatic module name "xchart" from the Jar file.

**Comment by timmolter** [comment]
Thanks. I'll take a close look at this early next week.

**Comment by timmolter** [comment]
<img width="866" alt="Screen Shot 2020-12-08 at 3 28 12 PM" src="https://user-images.githubusercontent.com/738972/101496468-15345580-396a-11eb-86d8-11909866dd34.png">

**Comment by timmolter** [comment]
I'll bump the version too.
