### ISSUE TITLE
Can't Get the Chart Started from Min value of 80? 

### ISSUE THREAD

**Issue by PrakashAdhikari08** [knowm/XChart#541]
I am trying to get the Chart being created Starting from 80 rather than 0. Have tried the max min function as well. Is there any possible solution for this please?

My code is:

 public String getChartXChart(){

        // Create Chart
        CategoryChart chart = new CategoryChartBuilder().width(500).height(350).title("Class Name and Year").xAxisTitle("").yAxisTitle("")
                .theme(Styler.ChartTheme.GGPlot2).build();

        List<String> categories = new ArrayList<>(Arrays.asList("Reading", "Writing", "Speaking", "Grammar & Punctuation", "Numeracy"));
        List<Integer> values = new ArrayList<>(Arrays.asList(83, 92, 93, 84,87));
        List<Integer> values1 = new ArrayList<>(Arrays.asList(80, 80, 83, 84, 87));
        List<Integer> values2 = new ArrayList<>(Arrays.asList(83, 82, 93, 94, 90));
        // Series
        chart.addSeries("2018", categories,
                values);
        chart.addSeries("2019", categories,
                values1);
        chart.addSeries("2020", categories,
               values2);
        chart.getStyler().setYAxisMin(80.0);
        chart.getStyler().setLegendLayout(Styler.LegendLayout.Horizontal);
        chart.getStyler().setLegendPosition(Styler.LegendPosition.OutsideS);
        chart.getStyler().setLegendFont(new Font("Bold", Font.PLAIN,10));
        chart.getStyler().setChartTitleBoxBackgroundColor(Color.WHITE);
        chart.getStyler().setChartTitleBoxBorderColor(Color.WHITE);
        chart.getStyler().setBaseFont(new Font("Bold", Font.PLAIN,9));
        chart.getStyler().setPlotMargin(0);
        chart.getStyler().setAxisTickLabelsFont(new Font("Bold", Font.PLAIN,9));
        chart.getStyler().setAxisTickLabelsColor(Color.BLACK);
        chart.getStyler().setAxisTickMarkLength(4);
        chart.getStyler().setLegendPadding(10);
        chart.getStyler().setPlotGridVerticalLinesVisible(false);
        chart.getStyler().setSeriesColors(new Color[]{  new Color(153, 0, 0),new Color(76,153,0),new Color(102, 178, 255),});
        try {
            BitmapEncoder.saveBitmap(chart,"./XChart", BitmapEncoder.BitmapFormat.PNG);
        } catch (IOException e) {
            e.printStackTrace();
        }
        return "Chart Created with XChart";
    }

The image generated is 
![XChart](https://user-images.githubusercontent.com/39783569/102178527-ae7ae300-3ef9-11eb-90c7-b6947cea7453.png)

Starts from 0.

**Comment by timmolter** [comment]
There's a bug in 3.6.6. Please either use 3.6.5 or the lastest snapshot. 3.7.0 should come out late this week.

**Comment by PrakashAdhikari08** [comment]
![XChart](https://user-images.githubusercontent.com/39783569/102180437-fa7b5700-3efc-11eb-8bc6-bacbeb7c8bfd.png)

3.6.5 release solves the 80 problems. Any methods that could make this an interval of 5 rather than 2 or auto.

**Comment by timmolter** [comment]
FYI, 3.7.0 released.
