### ISSUE TITLE
The new zoom feature breaks compatibility and does not work for heat maps and bar charts

### ISSUE THREAD

**Issue by mrcjkb** [knowm/XChart#547]
Hi.

I had my own external zoom and pan wrapper that relied on `Chart#getChartXFromCoordinate()` and `Chart#getChartYFromCoordinate`, which I had implemented for XYCharts, CategoryCharts and HeatMapCharts.

I see in the latest version, a zoom feature has been implemented for XYCharts and the aforementioned API has been removed.
However, the zoom feature has not (yet) been implemented for CategoryCharts or HeatMapCharts, preventing me from updating to the latest version.

Would it be possible to re-add the deleted API (and maybe mark the methods as deprecated) until zooming has been implemented for all chart types?

**Comment by landret** [comment]
Hi,
I have a similar issue. I am using v3.6.4 and using a child of SelectionZoom to customize its behavior : 
1) I added a mousewheel zoom
2) As I am also using real-time xychart with a huge quantity of data, I have to limit the number of points to display to limit CPU usage. When zooming, new points may be displayed.

**Comment by phraktle** [comment]
+1 for this. Since the axispair is not visible, there's no straightforward workaround for this.
