### ISSUE TITLE
Checkbox in labels

### ISSUE THREAD

**Issue by raulerasmolerma** [knowm/XChart#552]
If it's possible to set checkbox in the title lines to control which graph i want to see it?.. For example:
[ ] Line 1 
[ ] Line 2
[ x ] Line 3
In this case i want to see only the line 3. 

If I choose another one like this:
[ ] Line 1 
[ x ] Line 2
[ x ] Line 3
I must see the line 2 and 3 in the same graph..

If its possible? 

Regards, thanks

**Comment by mccartney** [comment]
AFAIK not possible as of now. It's a decent idea for a feature request.

**Comment by timmolter** [comment]
No, you'd have to wrap an XChartPanel in you Swing app and add the check boxes and handle the logic yourself.
