### ISSUE TITLE
[Feature request or Question] Callback for y-label formatting

### ISSUE THREAD

**Issue by MarkusKrug** [knowm/XChart#569]
Hi i wanna create an XY-chart which features "racing times" on the y-axis. They are formatted "minute:ss:mmm". What i would love to do is pass as x-values the date when the times were achieved and as y-values the times in millies. However seeing the times in millies is not really helpful, so i was hoping to get a callback when a y-value is to be displayed.

Thanks
Markus

**Comment by mccartney** [comment]
If I understand correctly, what you want to achieve is doable without a callback, a simple number format is enough.
To allow for providing a callback would be a different (and more powerful) feature.
