### ISSUE TITLE
How to display a chart into a JPanel?

### ISSUE THREAD

**Issue by samirfor** [knowm/XChart#59]
Hello, I was unable to insert a graphic within a JPanel. I found nothing like it in the examples. How do I?

**Comment by pwankhed** [comment]
The link is broken, can someone please share the correct link?

**Comment by timmolter** [comment]
https://github.com/knowm/XChart/blob/develop/xchart-demo/src/main/java/org/knowm/xchart/standalone/SwingDemo.java
