### ISSUE TITLE
Bug on CategoryStyler generating Area type charts

### ISSUE THREAD

**Issue by mmotta-zagile** [knowm/XChart#617]
**Description**
According to the charts offered by the library, when generating one of the **Area** type, the expected result does not match the one generated.

The issue is reproducible in:
Module Version: xchart.3.8.1
OS Version etc: Ubuntu 20.04.4 LTS

The steps to reproduce are:
Define a `new CategoryChart`
Set the `CategorySeriesRenderStyle` as an Area type.

```
final CategoryChart chart = new CategoryChartBuilder().width(chartWrapper.chartDimensions.get(1))
              .height(chartWrapper.chartDimensions.get(0)).build();
...
chart.getStyler().setPlotGridLinesColor(Color.GRAY);
chart.getStyler().setYAxisDecimalPattern(PATTERN);
chart.getStyler().setDefaultSeriesRenderStyle(CategorySeries.CategorySeriesRenderStyle.Area);
```

The expected result is:
![image](https://user-images.githubusercontent.com/58340891/129392398-abdce136-108a-4d03-bad8-bed6f1aeca8f.png)
Show a chart with the area below the boundary colored
The actual results is:
![image (1)](https://user-images.githubusercontent.com/58340891/129392431-6eac22c8-9f55-4882-a45f-3bd6bfa6077e.png)

It does not generate any error other than the visible one, a solution found is presented in the `Plot_Category` class as indicated by the attached `.txt` 
[xchart_3_8_1.txt](https://github.com/knowm/XChart/files/6984042/xchart_3_8_1.txt)

I've searched for any related issues and avoided creating a duplicate issue, thanks.

**Comment by mccartney** [comment]
Instead of attaching a patch file, I suggest you create a Pull Request toward the repository.

**Comment by timmolter** [comment]
i fixed this in a different way
