### ISSUE TITLE
XChart in Eclipse

### ISSUE THREAD

**Issue by LightMike** [knowm/XChart#620]
Hello Tim,
I am a very beginner in Java and would like to use XChart for a data plotting project.

Could you give me some quick hints, how to get XChart running in Eclipse.
Is it required to use Maven?

So far I referenced the xchart-3.8.1.jar in my Java project and created the Example0 class.

But this bings up the error message attached. For example2 I get error after run.

Regards,
Michael
![Example0](https://user-images.githubusercontent.com/71723869/132376832-6d7d0738-2c40-452a-842e-5a18a61a0937.JPG)

![Example1](https://user-images.githubusercontent.com/71723869/132377038-f8fb5868-9295-43a4-8f5c-474b3c929f35.JPG)

**Comment by timmolter** [comment]
Sorry, looks like something in your configuration is incorrect.
