### ISSUE TITLE
Grid line issues when using AxesChartStyler.setPlotGridLinesStroke

### ISSUE THREAD

**Issue by wborn** [knowm/XChart#628]
Since XChart 3.3.0 the grid lines appear multiple times when customizing them with `AxesChartStyler.setPlotGridLinesStroke`.

It can be reproduced using the small example program below:

```java
package example;

import java.awt.BasicStroke;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

import javax.swing.JFrame;
import javax.swing.JPanel;

import org.knowm.xchart.XYChart;
import org.knowm.xchart.XYChartBuilder;

public class ChartTest {

    private static class ChartPanel extends JPanel {

        private static final long serialVersionUID = 1L;

        @Override
        public void paint(Graphics g) {
            XYChart chart = new XYChartBuilder().width(getWidth()).height(getHeight()).build();
            chart.getStyler().setPlotGridLinesStroke(new BasicStroke((float) 3.125, BasicStroke.CAP_BUTT,
                    BasicStroke.JOIN_BEVEL, 10, new float[] { 6.25f, 6.25f }, 0));
            chart.paint((Graphics2D) g, chart.getWidth(), chart.getHeight());
        }
    }

    public static void main(String s[]) {
        JFrame frame = new JFrame();
        frame.getContentPane().add("Center", new ChartPanel());
        frame.pack();
        frame.setSize(new Dimension(500, 300));
        frame.setVisible(true);
        frame.setTitle("Chart Test");
        frame.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                System.exit(0);
            }
        });
    }

}
```

---

These are the resulting grid lines when running this program using XChart 3.8.1:

![xchart-3 8 1](https://user-images.githubusercontent.com/12213581/135732230-ba2c8b90-4701-4fce-95c2-16e56f23cc98.png)

---

If I run the same program using XChart 3.1.0 the grid lines look normal:

![xchart-3 1 0](https://user-images.githubusercontent.com/12213581/135732237-149f006d-3d6f-498a-a89e-e13726aa5087.png)

---

It seems the issues started with XChart 3.2.0 where the grid lines are not filled:

![xchart-3 2 0](https://user-images.githubusercontent.com/12213581/135732259-ba065b2c-5a32-4ea4-ae42-a40afc19fec4.png)

The [change log](https://knowm.org/open-source/xchart/xchart-change-log/) also mentions there was a fix for this in 3.3.0, but it looks like the fix had some side effects.

---

I've tested this on Java 11, Ubuntu 20.04.3

**Comment by Flole998** [comment]
@wborn I just provided a fix that seems to work for me. If you have some time, could you please confirm that it fixes our issue?

**Comment by wborn** [comment]
Thanks for the fix @Flole998! :+1:
I can confirm that it fixes the issue with my example program. :slightly_smiling_face:
