### ISSUE TITLE
can make jar file with maven

### ISSUE THREAD

**Issue by mikebgrep** [knowm/XChart#642]
`[ERROR] Error executing Maven.
[ERROR] java.lang.IllegalStateException: Unable to load cache item
[ERROR] Caused by: Unable to load cache item
[ERROR] Caused by: Could not initialize class com.google.inject.internal.cglib.core.$MethodWrapper
`
I am trying to build jar file to include in project but end up with this error when try to execute mvn clean package

**Comment by timmolter** [comment]
I'm not sure what the problem is. `mvn clean package` works here for me. I'm pretty sure that error is not related to XChart.

**Comment by mikebgrep** [comment]
Yes, the problem was with my maven. Sorry for misunderstood.
