### ISSUE TITLE
Incorrect Y-Axis for Category Chart when using Line Render Style

### ISSUE THREAD

**Issue by daniel-fontaine** [knowm/XChart#653]
The y-axis is incorrect for category chart when using line rendering style. The chart becomes correct if the y-axis min is explicitly set to 0 i.e. x chart.getStyler().setYAxisMin(0.0). If the y-axis min is set to something other than 0, the axes are again incorrect. This bug does not occur when using bar rendering style.

Example:

    double[] xData = new double[] { 0.0, 1.0, 2.0, 3.0, 4.0 };
	double[] yData = new double[] { 2.0, 1.5, 4.0, 3.77, 2.5 };
 
	// Create Chart
	CategoryChartBuilder builder = new CategoryChartBuilder();
	builder.title("Sample Chart")
	    .xAxisTitle("X")
	    .yAxisTitle("Y")
	    .theme(ChartTheme.Matlab);
	CategoryChart chart = builder.build();
	chart.getStyler().setDefaultSeriesRenderStyle(CategorySeries.CategorySeriesRenderStyle.Line);
	    //    .setYAxisMin(0.0);
	    
	chart.addSeries("y(x)", xData, yData);
 
	// Show it
	new SwingWrapper(chart).displayChart();

**Comment by jwedster** [comment]
Identified the same issue today. Thanks Daniel.

**Comment by timmolter** [comment]
Thanks. I'm looking at it now.

**Comment by timmolter** [comment]
Fixed. I'll push a release soon.

**Comment by daniel-fontaine** [comment]
Thanks Tim!
