### ISSUE TITLE
BitmapEncoder.saveBitmap doesn't work correctly

### ISSUE THREAD

**Issue by tutories** [knowm/XChart#724]
Hello,

The BitmapEncoder function does not correctly encode the image, in any of its variants, using jdk-8u152 with glassfish5.1. With java11 and Tomcat9 it seems that it works. Some image examples are attached.

Could you review it? It would be great that if works for java 1.8

Thank you very much!!

                BitmapEncoder.saveBitmap(chart, "provaimatge3.png", BitmapEncoder.BitmapFormat.PNG);
                BitmapEncoder.saveBitmap(chart, "provaimatge4.jpg", BitmapEncoder.BitmapFormat.JPG);
                BitmapEncoder.saveBitmap(chart, "provaimatge5.bmp", BitmapEncoder.BitmapFormat.BMP);
                BitmapEncoder.saveJPGWithQuality(chart, "provaimatge6.jpg", 1);                
                BitmapEncoder.saveBitmapWithDPI(chart, "provaimatge7.jpg", BitmapEncoder.BitmapFormat.PNG, 300);

![provaimatge3](https://user-images.githubusercontent.com/109586087/212134375-1334a2f5-1c1b-4644-b945-940dcd42ac22.png)
![provaimatge4](https://user-images.githubusercontent.com/109586087/212134376-cc5f344e-0a2f-42de-b6ef-397ac405aa07.jpg)

**Comment by mccartney** [comment]
I think more information would be needed in order to pin point the supposed bug. It might look like an infra issue to me (different OS fonts installed, etc.)

**Comment by tutories** [comment]
Hi, 
I updated java to java11 and now it works.
Thanks.
