### ISSUE TITLE
Upgrade to de.rototor.pdfbox:graphics2d 3.0.1

### ISSUE THREAD

**Issue by carlosame** [knowm/XChart#810]
XChart currently uses version 3.0.0 of `de.rototor.pdfbox:graphics2d` which is unusable in modular projects, see rototor/pdfbox-graphics2d#56 and also [PDFBOX-5664](https://issues.apache.org/jira/browse/PDFBOX-5664).

In my project I obtain a number of errors similar to this:

```
error: module org.knowm.xchart reads package org.apache.pdfbox.multipdf from both org.apache.pdfbox and de.rototor.pdfbox.graphics2d
```

Please upgrade to 3.0.1 which fixes this.

**Comment by timmolter** [comment]
Thanks for letting me know. Will do ASAP.

**Comment by timmolter** [comment]
done.

**Comment by carlosame** [comment]
Thank you.
