### ISSUE TITLE
Feature Request: Enforce Different Colors for Up and Down Candles in OHLC Chart

### ISSUE THREAD

**Issue by phandduong-98** [knowm/XChart#850]
I am using the XChart library to create OHLC charts and noticed that it's currently possible to set the same color for both up and down candles. This can be misleading in financial charts as it defeats the purpose of quick visual cues distinguishing between positive and negative market movements.
**Proposed Feature:**
Enforce distinct color settings for up and down candles in the OHLC charts. This will ensure that the charts are not only informative but also visually intuitive.
Thank you for considering this feature. I look forward to your feedback.

**Comment by mccartney** [comment]
> Enforce

Not sure if this should be enforced.

Probably safer is to offer it as an **option**.
