### ISSUE TITLE
OHLC Charts

### ISSUE THREAD

**Issue by dkcm** [knowm/XChart#94]
Great job on XChart.  Any chance of implementing the above in the near future?

**Comment by timmolter** [comment]
It's planned, but could take a while as free time is scarce these days. I'd pay someone to do it if you know of anyone.

**Comment by dkcm** [comment]
Bounty time!

**Comment by MartyIX** [comment]
@timmolter This feature was released, wasn't it? I suppose the issue can be closed. :-)
